{{ config(materialized='view', tags=['healthcare_event_stream']) }}

with source_records as (
select
    event_id,
    sk_patient_id,
    source_person_id,
    source_dataset,
    source_record_type,
    source_record_id,
    source_model_name,
    event_date,
    event_at,
    event_time_precision,
    event_time_basis,
    event_type,
    event_name,
    null::varchar as event_code,
    null::varchar as event_code_name,
    null::varchar as event_coding_system,
    care_setting,
    null::varchar as status_code,
    null::varchar as status_name,
    attendance_code,
    attendance_name,
    null::varchar as outcome_code,
    null::varchar as outcome_name,
    service_or_team_type_code,
    service_or_team_type_name,
    null::varchar as specialty_code,
    null::varchar as specialty_name,
    consultation_mechanism_code,
    consultation_mechanism_name,
    activity_location_type_code,
    activity_location_type_name,
    provider_organisation_code,
    provider_organisation_name,
    provider_code_authority,
    site_code,
    site_name,
    referring_organisation_code,
    referring_organisation_name,
    null::varchar as clinical_record_id,
    parent_record_type,
    parent_record_id,
    parent_model_name,
    relationship_type,
    source_submission_period,
    source_received_at,
    initcap(replace(care_setting, '_', ' ')) as care_setting_name,
    null::varchar as service_id,
    null::varchar as service_name,
    null::varchar as priority_code,
    null::varchar as priority_name
from {{ ref('int_mhsds_healthcare_event') }}
union all
select
    event_id,
    sk_patient_id,
    source_person_id,
    source_dataset,
    source_record_type,
    source_record_id,
    source_model_name,
    event_date,
    event_at,
    event_time_precision,
    event_time_basis,
    event_type,
    event_name,
    null::varchar as event_code,
    null::varchar as event_code_name,
    null::varchar as event_coding_system,
    care_setting,
    null::varchar as status_code,
    null::varchar as status_name,
    attendance_code,
    attendance_name,
    null::varchar as outcome_code,
    null::varchar as outcome_name,
    null::varchar as service_or_team_type_code,
    null::varchar as service_or_team_type_name,
    null::varchar as specialty_code,
    null::varchar as specialty_name,
    consultation_mechanism_code,
    consultation_mechanism_name,
    activity_location_type_code,
    activity_location_type_name,
    provider_organisation_code,
    provider_organisation_name,
    provider_code_authority,
    site_code,
    site_name,
    referring_organisation_code,
    referring_organisation_name,
    null::varchar as clinical_record_id,
    parent_record_type,
    parent_record_id,
    parent_model_name,
    relationship_type,
    source_submission_period,
    source_received_at,
    initcap(replace(care_setting, '_', ' ')) as care_setting_name,
    null::varchar as service_id,
    null::varchar as service_name,
    null::varchar as priority_code,
    null::varchar as priority_name
from {{ ref('int_csds_healthcare_event') }}
union all
select
    event_id,
    sk_patient_id,
    source_person_id,
    source_dataset,
    source_record_type,
    source_record_id,
    source_model_name,
    event_date,
    event_at,
    event_time_precision,
    event_time_basis,
    event_type,
    event_name,
    event_code,
    event_code_name,
    event_coding_system,
    care_setting,
    status_code,
    status_name,
    null::varchar as attendance_code,
    null::varchar as attendance_name,
    null::varchar as outcome_code,
    null::varchar as outcome_name,
    null::varchar as service_or_team_type_code,
    null::varchar as service_or_team_type_name,
    null::varchar as specialty_code,
    null::varchar as specialty_name,
    null::varchar as consultation_mechanism_code,
    null::varchar as consultation_mechanism_name,
    null::varchar as activity_location_type_code,
    null::varchar as activity_location_type_name,
    provider_organisation_code,
    provider_organisation_name,
    provider_code_authority,
    null::varchar as site_code,
    null::varchar as site_name,
    null::varchar as referring_organisation_code,
    null::varchar as referring_organisation_name,
    clinical_record_id,
    null::varchar as parent_record_type,
    null::varchar as parent_record_id,
    null::varchar as parent_model_name,
    null::varchar as relationship_type,
    null::date as source_submission_period,
    source_received_at,
    initcap(replace(care_setting, '_', ' ')) as care_setting_name,
    null::varchar as service_id,
    null::varchar as service_name,
    null::varchar as priority_code,
    null::varchar as priority_name
from {{ ref('int_olids_healthcare_event') }}
union all
select
    event_id,
    sk_patient_id,
    null::varchar as source_person_id,
    source_dataset,
    source_record_type,
    source_record_id,
    source_model_name,
    event_date,
    event_at,
    event_time_precision,
    event_time_basis,
    event_type,
    event_name,
    null::varchar as event_code,
    null::varchar as event_code_name,
    null::varchar as event_coding_system,
    care_setting,
    null::varchar as status_code,
    null::varchar as status_name,
    attendance_code,
    attendance_name,
    outcome_code,
    outcome_name,
    null::varchar as service_or_team_type_code,
    null::varchar as service_or_team_type_name,
    specialty_code,
    specialty_name,
    null::varchar as consultation_mechanism_code,
    null::varchar as consultation_mechanism_name,
    null::varchar as activity_location_type_code,
    null::varchar as activity_location_type_name,
    provider_organisation_code,
    provider_organisation_name,
    provider_code_authority,
    site_code,
    site_name,
    null::varchar as referring_organisation_code,
    null::varchar as referring_organisation_name,
    null::varchar as clinical_record_id,
    null::varchar as parent_record_type,
    null::varchar as parent_record_id,
    null::varchar as parent_model_name,
    null::varchar as relationship_type,
    null::date as source_submission_period,
    source_received_at,
    initcap(replace(care_setting, '_', ' ')) as care_setting_name,
    null::varchar as service_id,
    null::varchar as service_name,
    null::varchar as priority_code,
    null::varchar as priority_name
from {{ ref('int_sus_healthcare_event') }}
union all
select
    event_id,
    sk_patient_id,
    null::varchar as source_person_id,
    source_dataset,
    source_record_type,
    source_record_id,
    source_model_name,
    event_date,
    event_at,
    event_time_precision,
    event_time_basis,
    event_type,
    event_name,
    event_code,
    event_code_name,
    event_coding_system,
    null::varchar as care_setting,
    null::varchar as status_code,
    null::varchar as status_name,
    null::varchar as attendance_code,
    null::varchar as attendance_name,
    outcome_code,
    outcome_name,
    null::varchar as service_or_team_type_code,
    null::varchar as service_or_team_type_name,
    specialty_code,
    specialty_name,
    null::varchar as consultation_mechanism_code,
    null::varchar as consultation_mechanism_name,
    null::varchar as activity_location_type_code,
    null::varchar as activity_location_type_name,
    provider_organisation_code,
    provider_organisation_name,
    provider_code_authority,
    site_code,
    site_name,
    referring_organisation_code,
    referring_organisation_name,
    null::varchar as clinical_record_id,
    parent_record_type,
    parent_record_id,
    parent_model_name,
    relationship_type,
    null::date as source_submission_period,
    source_received_at,
    null::varchar as care_setting_name,
    service_id,
    service_name,
    priority_code,
    priority_name
from {{ ref('int_ers_healthcare_event') }}
)
select
    sk_patient_id,
    case
        when event_time_precision = 'timestamp' then event_at
        when event_time_precision = 'month' then date_trunc('month', event_date)::timestamp_ntz
        when event_time_precision = 'year' then date_trunc('year', event_date)::timestamp_ntz
        else event_date::timestamp_ntz
    end as event_at,
    event_date,
    event_time_precision,
    event_time_basis,
    event_type,
    event_name,
    event_code,
    event_code_name,
    event_coding_system,
    care_setting,
    care_setting_name,
    status_code,
    status_name,
    attendance_code as attendance_status_code,
    attendance_name as attendance_status_name,
    outcome_code,
    outcome_name,
    service_id,
    service_name,
    priority_code,
    priority_name,
    service_or_team_type_code,
    service_or_team_type_name,
    specialty_code,
    specialty_name,
    consultation_mechanism_code,
    consultation_mechanism_name,
    activity_location_type_code,
    activity_location_type_name,
    provider_organisation_code,
    provider_organisation_name,
    provider_code_authority,
    site_code,
    site_name,
    referring_organisation_code,
    referring_organisation_name,
    event_id,
    clinical_record_id,
    source_dataset,
    source_person_id,
    source_record_type,
    source_record_id,
    source_model_name,
    parent_record_type,
    parent_record_id,
    parent_model_name,
    relationship_type,
    source_submission_period,
    source_received_at
from source_records

-- Midnight and period starts are sorting anchors, not observed clock times.
order by sk_patient_id nulls last, event_at nulls last, event_id
