{{ config(materialized='view', tags=['person_clinical_record']) }}

select
    clinical_record_id,
    sk_patient_id,
    source_person_id,
    source_dataset,
    source_record_type,
    source_record_id,
    source_model_name,
    provider_organisation_code,
    provider_organisation_name,
    provider_code_authority,
    parent_record_type,
    parent_record_id,
    parent_model_name,
    relationship_type,
    source_submission_period,
    source_received_at,
    clinical_record_type,
    clinical_record_date,
    clinical_record_at,
    clinical_time_precision,
    clinical_time_basis,
    source_code,
    source_code_name,
    source_coding_system,
    mapped_code,
    mapped_code_name,
    mapped_coding_system,
    result_value,
    result_value_name,
    result_value_numeric,
    result_value_parse_status,
    null::date as result_date,
    result_unit_code,
    result_unit_name,
    result_unit_symbol,
    null::varchar as medication_name,
    null::varchar as medication_dose,
    null::float as medication_quantity_value,
    null::varchar as medication_quantity_unit,
    null::number(38,0) as medication_duration_days,
    null::varchar as medication_authorisation_type_code,
    null::varchar as medication_authorisation_type_name,
    null::varchar as qualifier_code,
    null::varchar as qualifier_name,
    initcap(replace(clinical_record_type, '_', ' ')) as clinical_record_type_name
from {{ ref('int_mhsds_person_clinical_record') }}
union all
select
    clinical_record_id,
    sk_patient_id,
    source_person_id,
    source_dataset,
    source_record_type,
    source_record_id,
    source_model_name,
    provider_organisation_code,
    provider_organisation_name,
    provider_code_authority,
    parent_record_type,
    parent_record_id,
    parent_model_name,
    relationship_type,
    source_submission_period,
    source_received_at,
    clinical_record_type,
    clinical_record_date,
    clinical_record_at,
    clinical_time_precision,
    clinical_time_basis,
    source_code,
    source_code_name,
    source_coding_system,
    mapped_code,
    mapped_code_name,
    mapped_coding_system,
    result_value,
    result_value_name,
    result_value_numeric,
    result_value_parse_status,
    null::date as result_date,
    result_unit_code,
    result_unit_name,
    result_unit_symbol,
    null::varchar as medication_name,
    null::varchar as medication_dose,
    null::float as medication_quantity_value,
    null::varchar as medication_quantity_unit,
    null::number(38,0) as medication_duration_days,
    null::varchar as medication_authorisation_type_code,
    null::varchar as medication_authorisation_type_name,
    null::varchar as qualifier_code,
    null::varchar as qualifier_name,
    initcap(replace(clinical_record_type, '_', ' ')) as clinical_record_type_name
from {{ ref('int_csds_person_clinical_record') }}
union all
select
    clinical_record_id,
    sk_patient_id,
    source_person_id,
    source_dataset,
    source_record_type,
    source_record_id,
    source_model_name,
    provider_organisation_code,
    provider_organisation_name,
    provider_code_authority,
    parent_record_type,
    parent_record_id,
    parent_model_name,
    relationship_type,
    null::date as source_submission_period,
    source_received_at,
    clinical_record_type,
    clinical_record_date,
    null::timestamp_ntz as clinical_record_at,
    clinical_time_precision,
    clinical_time_basis,
    source_code,
    source_code_name,
    source_coding_system,
    mapped_code,
    mapped_code_name,
    mapped_coding_system,
    result_value,
    null::varchar as result_value_name,
    result_value_numeric,
    result_value_parse_status,
    result_date,
    result_unit_code,
    result_unit_name,
    null::varchar as result_unit_symbol,
    medication_name,
    medication_dose,
    medication_quantity_value,
    medication_quantity_unit,
    medication_duration_days,
    medication_authorisation_type_code,
    medication_authorisation_type_name,
    null::varchar as qualifier_code,
    null::varchar as qualifier_name,
    initcap(replace(clinical_record_type, '_', ' ')) as clinical_record_type_name
from {{ ref('int_olids_person_clinical_record') }}
union all
select
    clinical_record_id,
    sk_patient_id,
    null::varchar as source_person_id,
    source_dataset,
    source_record_type,
    source_record_id,
    source_model_name,
    provider_organisation_code,
    provider_organisation_name,
    provider_code_authority,
    parent_record_type,
    parent_record_id,
    parent_model_name,
    relationship_type,
    null::date as source_submission_period,
    source_received_at,
    clinical_record_type,
    clinical_record_date,
    null::timestamp_ntz as clinical_record_at,
    clinical_time_precision,
    clinical_time_basis,
    source_code,
    source_code_name,
    source_coding_system,
    null::varchar as mapped_code,
    null::varchar as mapped_code_name,
    null::varchar as mapped_coding_system,
    null::varchar as result_value,
    null::varchar as result_value_name,
    null::number(38,9) as result_value_numeric,
    null::varchar as result_value_parse_status,
    null::date as result_date,
    null::varchar as result_unit_code,
    null::varchar as result_unit_name,
    null::varchar as result_unit_symbol,
    null::varchar as medication_name,
    null::varchar as medication_dose,
    null::float as medication_quantity_value,
    null::varchar as medication_quantity_unit,
    null::number(38,0) as medication_duration_days,
    null::varchar as medication_authorisation_type_code,
    null::varchar as medication_authorisation_type_name,
    null::varchar as qualifier_code,
    null::varchar as qualifier_name,
    initcap(replace(clinical_record_type, '_', ' ')) as clinical_record_type_name
from {{ ref('int_sus_person_clinical_record') }}
union all
select
    clinical_record_id,
    sk_patient_id,
    null::varchar as source_person_id,
    source_dataset,
    source_record_type,
    source_record_id,
    source_model_name,
    provider_organisation_code,
    provider_organisation_name,
    provider_code_authority,
    parent_record_type,
    parent_record_id,
    parent_model_name,
    relationship_type,
    null::date as source_submission_period,
    source_received_at,
    clinical_record_type,
    clinical_record_date,
    clinical_record_at,
    clinical_time_precision,
    clinical_time_basis,
    source_code,
    source_code_name,
    source_coding_system,
    null::varchar as mapped_code,
    null::varchar as mapped_code_name,
    null::varchar as mapped_coding_system,
    null::varchar as result_value,
    null::varchar as result_value_name,
    null::number(38,9) as result_value_numeric,
    null::varchar as result_value_parse_status,
    null::date as result_date,
    null::varchar as result_unit_code,
    null::varchar as result_unit_name,
    null::varchar as result_unit_symbol,
    null::varchar as medication_name,
    null::varchar as medication_dose,
    null::float as medication_quantity_value,
    null::varchar as medication_quantity_unit,
    null::number(38,0) as medication_duration_days,
    null::varchar as medication_authorisation_type_code,
    null::varchar as medication_authorisation_type_name,
    qualifier_code,
    qualifier_name,
    initcap(replace(clinical_record_type, '_', ' ')) as clinical_record_type_name
from {{ ref('int_ecds_person_clinical_record') }}

-- Date-only rows follow timed rows on their day without implying an actual sequence.
order by sk_patient_id nulls last, clinical_record_date nulls last,
    clinical_record_at nulls last, clinical_record_id
