{{
    config(
        description="Raw layer: Code definitions by ECDS specification file and sheet. 1:1 passthrough with cleaned column names. \nSource: UKHFD.ECDS_TOS.dim_Code_Sets \ndbt: source(''ukhfd_ecds_tos'', ''ecds_code_sets'') \nColumns:\n  Sheet_Name -> sheet_name\n  ECDS_UniqueID -> ecds_unique_id\n  Sort1 -> sort1\n  Sort2 -> sort2\n  Sort3 -> sort3\n  ECDS_Group1 -> ecds_group1\n  ECDS_Group2 -> ecds_group2\n  ECDS_Group3 -> ecds_group3\n  ECDS_Description -> ecds_description\n  ECDS_SearchTerms -> ecds_search_terms\n  SNOMED_Code -> snomed_code\n  SNOMED_Description -> snomed_description\n  SNOMED_TERM -> snomed_term\n  Flag_Inj -> flag_inj\n  Flag_AEC -> flag_aec\n  Flag_Allergy -> flag_allergy\n  Flag_NotifiableDisease -> flag_notifiable_disease\n  Flag_Injury -> flag_injury\n  Flag_Male -> flag_male\n  Flag_Female -> flag_female\n  Parent_Term -> parent_term\n  Maps_To_Self -> maps_to_self\n  ECDS_Notes -> ecds_notes\n  Notes -> notes\n  CDS10_Mapping_Diagnosis_Condition -> cds10_mapping_diagnosis_condition\n  CDS10_Mapping_Sub_Analysis_Code -> cds10_mapping_sub_analysis_code\n  CDS10_Mapping_Anatomical_Area -> cds10_mapping_anatomical_area\n  CDS_Code_Mapping_Used_For_HRG_Grouping -> cds_code_mapping_used_for_hrg_grouping\n  PbR_Category -> pb_r_category\n  CDS_Investigation_Mapping_That_Is_Used_For_HRG_Grouping -> cds_investigation_mapping_that_is_used_for_hrg_grouping\n  CDS_Treatment_Mapping_That_Is_Used_For_HRG_Grouping -> cds_treatment_mapping_that_is_used_for_hrg_grouping\n  ICD10_Mapping -> icd10_mapping\n  Valid_From -> valid_from\n  Valid_To -> valid_to\n  Notes_For_Completing_The_Observation_Value_Field -> notes_for_completing_the_observation_value_field\n  Flag_SDEC -> flag_sdec\n  Core_List_Term -> core_list_term\n  Core_List_Term_Description -> core_list_term_description\n  Chief_Complaint_Core_List -> chief_complaint_core_list\n  Chief_Complaint_Max_List -> chief_complaint_max_list\n  SNOMED_UK_Preferred_Term -> snomed_uk_preferred_term\n  SNOMED_Fully_Specified_Name -> snomed_fully_specified_name\n  Flag_ADS -> flag_ads\n  Sort4 -> sort4\n  ICD10_Description -> icd10_description\n  ICD11_Mapping -> icd11_mapping\n  ICD11_Description -> icd11_description\n  REFSET_UniqueID -> refset_unique_id\n  Flag_Pain -> flag_pain\n  ICD10_Code -> icd10_code\n  Charlson -> charlson\n  Elixhauser -> elixhauser\n  File_Name -> file_name\n  Unique_Column -> unique_column\n  Import_Date -> import_date\n  Created_Date -> created_date"
    )
}}
select
    "Sheet_Name" as sheet_name,
    "ECDS_UniqueID" as ecds_unique_id,
    "Sort1" as sort1,
    "Sort2" as sort2,
    "Sort3" as sort3,
    "ECDS_Group1" as ecds_group1,
    "ECDS_Group2" as ecds_group2,
    "ECDS_Group3" as ecds_group3,
    "ECDS_Description" as ecds_description,
    "ECDS_SearchTerms" as ecds_search_terms,
    "SNOMED_Code" as snomed_code,
    "SNOMED_Description" as snomed_description,
    "SNOMED_TERM" as snomed_term,
    "Flag_Inj" as flag_inj,
    "Flag_AEC" as flag_aec,
    "Flag_Allergy" as flag_allergy,
    "Flag_NotifiableDisease" as flag_notifiable_disease,
    "Flag_Injury" as flag_injury,
    "Flag_Male" as flag_male,
    "Flag_Female" as flag_female,
    "Parent_Term" as parent_term,
    "Maps_To_Self" as maps_to_self,
    "ECDS_Notes" as ecds_notes,
    "Notes" as notes,
    "CDS10_Mapping_Diagnosis_Condition" as cds10_mapping_diagnosis_condition,
    "CDS10_Mapping_Sub_Analysis_Code" as cds10_mapping_sub_analysis_code,
    "CDS10_Mapping_Anatomical_Area" as cds10_mapping_anatomical_area,
    "CDS_Code_Mapping_Used_For_HRG_Grouping" as cds_code_mapping_used_for_hrg_grouping,
    "PbR_Category" as pb_r_category,
    "CDS_Investigation_Mapping_That_Is_Used_For_HRG_Grouping" as cds_investigation_mapping_that_is_used_for_hrg_grouping,
    "CDS_Treatment_Mapping_That_Is_Used_For_HRG_Grouping" as cds_treatment_mapping_that_is_used_for_hrg_grouping,
    "ICD10_Mapping" as icd10_mapping,
    "Valid_From" as valid_from,
    "Valid_To" as valid_to,
    "Notes_For_Completing_The_Observation_Value_Field" as notes_for_completing_the_observation_value_field,
    "Flag_SDEC" as flag_sdec,
    "Core_List_Term" as core_list_term,
    "Core_List_Term_Description" as core_list_term_description,
    "Chief_Complaint_Core_List" as chief_complaint_core_list,
    "Chief_Complaint_Max_List" as chief_complaint_max_list,
    "SNOMED_UK_Preferred_Term" as snomed_uk_preferred_term,
    "SNOMED_Fully_Specified_Name" as snomed_fully_specified_name,
    "Flag_ADS" as flag_ads,
    "Sort4" as sort4,
    "ICD10_Description" as icd10_description,
    "ICD11_Mapping" as icd11_mapping,
    "ICD11_Description" as icd11_description,
    "REFSET_UniqueID" as refset_unique_id,
    "Flag_Pain" as flag_pain,
    "ICD10_Code" as icd10_code,
    "Charlson" as charlson,
    "Elixhauser" as elixhauser,
    "File_Name" as file_name,
    "Unique_Column" as unique_column,
    "Import_Date" as import_date,
    "Created_Date" as created_date
from {{ source('ukhfd_ecds_tos', 'ecds_code_sets') }}
