{{
    config(
        description="Raw layer (Data management reference datasets). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE__NCL.DATA_MANAGEMENT.VW_WNL_GP_PRACTICE_COMPLETE_SIZES \ndbt: source(''reference_data_management'', ''VW_WNL_GP_PRACTICE_COMPLETE_SIZES'') \nColumns:\n  ORGANISATION_CODE -> organisation_code\n  ORGANISATION_NAME -> organisation_name\n  SUB_ICB_CODE -> sub_icb_code\n  STATUS -> status\n  ORGANISATION_PRIMARY_ROLE -> organisation_primary_role\n  LATEST_REG_LIST_SIZE -> latest_reg_list_size\n  WEIGHTED_LIST_SIZE -> weighted_list_size\n  Q1_PRACTICE_LIST_SIZE -> q1_practice_list_size\n  Q1_WEIGHTED_LIST_SIZE -> q1_weighted_list_size\n  Q1_NORMALISED_LIST_SIZE -> q1_normalised_list_size\n  Q1_QUARTER_DATE -> q1_quarter_date\n  Q1_COMMISSIONER_CODE -> q1_commissioner_code\n  Q1_COMMISSIONER_NAME -> q1_commissioner_name\n  Q1_PRACTICE_NAME_FROM_Q1 -> q1_practice_name_from_q1\n  SK_ORGANISATION_ID_PARENT_ORG -> sk_organisation_id_parent_org\n  SK_ORGANISATION_ID_CURRENT_CARE_ORG -> sk_organisation_id_current_care_org\n  SK_ORGANISATION_ID_NATIONAL_GROUPING -> sk_organisation_id_national_grouping\n  SK_ORGANISATION_ID_HEALTH_AUTHORITY -> sk_organisation_id_health_authority\n  UPRN -> uprn\n  COUNTRY -> country\n  ADDRESS_LINE_1 -> address_line_1\n  ADDRESS_LINE_2 -> address_line_2\n  ADDRESS_LINE_3 -> address_line_3\n  ADDRESS_LINE_4 -> address_line_4\n  ADDRESS_LINE_5 -> address_line_5\n  SK_POSTCODE_ID -> sk_postcode_id\n  START_DATE -> start_date\n  END_DATE -> end_date\n  START_DATE_LEGAL -> start_date_legal\n  END_DATE_LEGAL -> end_date_legal\n  START_DATE_OPERATIONAL -> start_date_operational\n  END_DATE_OPERATIONAL -> end_date_operational\n  JOIN_PARENT_DATE -> join_parent_date\n  LEFT_PARENT_DATE -> left_parent_date\n  SK_ORGANISATION_ID -> sk_organisation_id\n  SK_ORGANISATION_TYPE_ID -> sk_organisation_type_id\n  SK_PRESCRIBING_SETTING_ID -> sk_prescribing_setting_id\n  SK_ORGANISATION_STATUS_ID -> sk_organisation_status_id\n  CODE_ASSIGNED_BY -> code_assigned_by\n  FIRST_CREATED -> first_created\n  LAST_UPDATED -> last_updated\n  LAST_CHANGE_DATE -> last_change_date\n  Q1_LAST_UPDATED -> q1_last_updated\n  DATA_LAKE_REFRESH_DATE -> data_lake_refresh_date\n  DATA_LAKE_MODIFIED_BY -> data_lake_modified_by"
    )
}}
select
    "ORGANISATION_CODE" as organisation_code,
    "ORGANISATION_NAME" as organisation_name,
    "SUB_ICB_CODE" as sub_icb_code,
    "STATUS" as status,
    "ORGANISATION_PRIMARY_ROLE" as organisation_primary_role,
    "LATEST_REG_LIST_SIZE" as latest_reg_list_size,
    "WEIGHTED_LIST_SIZE" as weighted_list_size,
    "Q1_PRACTICE_LIST_SIZE" as q1_practice_list_size,
    "Q1_WEIGHTED_LIST_SIZE" as q1_weighted_list_size,
    "Q1_NORMALISED_LIST_SIZE" as q1_normalised_list_size,
    "Q1_QUARTER_DATE" as q1_quarter_date,
    "Q1_COMMISSIONER_CODE" as q1_commissioner_code,
    "Q1_COMMISSIONER_NAME" as q1_commissioner_name,
    "Q1_PRACTICE_NAME_FROM_Q1" as q1_practice_name_from_q1,
    "SK_ORGANISATION_ID_PARENT_ORG" as sk_organisation_id_parent_org,
    "SK_ORGANISATION_ID_CURRENT_CARE_ORG" as sk_organisation_id_current_care_org,
    "SK_ORGANISATION_ID_NATIONAL_GROUPING" as sk_organisation_id_national_grouping,
    "SK_ORGANISATION_ID_HEALTH_AUTHORITY" as sk_organisation_id_health_authority,
    "UPRN" as uprn,
    "COUNTRY" as country,
    "ADDRESS_LINE_1" as address_line_1,
    "ADDRESS_LINE_2" as address_line_2,
    "ADDRESS_LINE_3" as address_line_3,
    "ADDRESS_LINE_4" as address_line_4,
    "ADDRESS_LINE_5" as address_line_5,
    "SK_POSTCODE_ID" as sk_postcode_id,
    "START_DATE" as start_date,
    "END_DATE" as end_date,
    "START_DATE_LEGAL" as start_date_legal,
    "END_DATE_LEGAL" as end_date_legal,
    "START_DATE_OPERATIONAL" as start_date_operational,
    "END_DATE_OPERATIONAL" as end_date_operational,
    "JOIN_PARENT_DATE" as join_parent_date,
    "LEFT_PARENT_DATE" as left_parent_date,
    "SK_ORGANISATION_ID" as sk_organisation_id,
    "SK_ORGANISATION_TYPE_ID" as sk_organisation_type_id,
    "SK_PRESCRIBING_SETTING_ID" as sk_prescribing_setting_id,
    "SK_ORGANISATION_STATUS_ID" as sk_organisation_status_id,
    "CODE_ASSIGNED_BY" as code_assigned_by,
    "FIRST_CREATED" as first_created,
    "LAST_UPDATED" as last_updated,
    "LAST_CHANGE_DATE" as last_change_date,
    "Q1_LAST_UPDATED" as q1_last_updated,
    "DATA_LAKE_REFRESH_DATE" as data_lake_refresh_date,
    "DATA_LAKE_MODIFIED_BY" as data_lake_modified_by
from {{ source('reference_data_management', 'VW_WNL_GP_PRACTICE_COMPLETE_SIZES') }}
