{{
    config(
        description="Raw layer (Project Myria (BEVC) canonical inputs - Doccla enrolled patients and the propensity-matched evaluation population. One row per patient per file; FILE_DATE identifies the upload. Loaded by MYRIA.LOAD_NEW_FILES().). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE__NCL.MYRIA.MATCHED_PATIENTS \ndbt: source(''myria'', ''MATCHED_PATIENTS'') \nColumns:\n  PATIENT_ID -> patient_id\n  HEX_ID -> hex_id\n  ON_PDS_DEMOG -> on_pds_demog\n  IS_MATCH_OLIDS -> is_match_olids\n  IS_ACTIVE -> is_active\n  INACTIVE_REASON -> inactive_reason\n  DEATH_DATE -> death_date\n  FIRST_FILE_DATE -> first_file_date\n  LOCAL_AUTHORITY -> local_authority\n  ENROLLED -> enrolled\n  ENROLLED_DATE -> enrolled_date\n  ONBOARDED -> onboarded\n  ONBOARDED_DATE -> onboarded_date\n  DAYS_ONBOARDED -> days_onboarded\n  DISCHARGED -> discharged\n  DISCHARGED_DATE -> discharged_date\n  GENDER -> gender\n  AGE_YEARS -> age_years\n  IMD_DECILE -> imd_decile\n  IS_CARE_HOME -> is_care_home\n  ETHNICITY_GROUP -> ethnicity_group\n  MOST_RECENT_NEL_ADMISSION_DATE -> most_recent_nel_admission_date\n  DAYS_SINCE_NEL_ADMISSION -> days_since_nel_admission\n  NEL_ADMISSIONS_2_YEARS -> nel_admissions_2_years\n  BARNET_HOSPITAL_COUNT -> barnet_hospital_count\n  RFL_COUNT -> rfl_count\n  TOTAL_HIGH_RISK_CONDITIONS -> total_high_risk_conditions\n  ALCOHOL_DEPENDENCE -> alcohol_dependence\n  ATRIAL_FIBRILLATION -> atrial_fibrillation\n  BRONCHIECTASIS -> bronchiectasis\n  CEREBROVASCULAR_DISEASE -> cerebrovascular_disease\n  CHRONIC_KIDNEY_DISEASE -> chronic_kidney_disease\n  CHRONIC_LIVER_DISEASE -> chronic_liver_disease\n  COPD -> copd\n  CORONARY_HEART_DISEASE -> coronary_heart_disease\n  DEMENTIA -> dementia\n  END_STAGE_RENAL_FAILURE -> end_stage_renal_failure\n  FRAILTY_FALLS -> frailty_falls\n  HEART_FAILURE -> heart_failure\n  HYPERTENSION -> hypertension\n  LIVER_FAILURE -> liver_failure\n  OSTEOPOROSIS -> osteoporosis\n  PARKINSONS_DISEASE -> parkinsons_disease\n  PERIPHERAL_VASCULAR_DISEASE -> peripheral_vascular_disease\n  PULMONARY_HEART_DISEASE -> pulmonary_heart_disease\n  RHEUMATOID_ARTHRITIS -> rheumatoid_arthritis\n  SEVERE_INTERSTITIAL_LUNG_DISEASE -> severe_interstitial_lung_disease\n  AGE_BAND -> age_band\n  DAYS_BAND -> days_band\n  MONTHS_ELIGIBLE -> months_eligible\n  ETH_WHITE -> eth_white\n  ETH_MIXED -> eth_mixed\n  ETH_ASIAN -> eth_asian\n  ETH_BLACK -> eth_black\n  ETH_OTHER -> eth_other\n  _GROUP -> group_value\n  PROPENSITY_SCORE -> propensity_score\n  MATCH_ID -> match_id\n  MATCH_DISTANCE -> match_distance\n  IS_OPTED_IN -> is_opted_in\n  FILE_DATE -> file_date\n  SOURCE_FILE -> source_file\n  LOADED_AT -> loaded_at"
    )
}}
select
    "PATIENT_ID" as patient_id,
    "HEX_ID" as hex_id,
    "ON_PDS_DEMOG" as on_pds_demog,
    "IS_MATCH_OLIDS" as is_match_olids,
    "IS_ACTIVE" as is_active,
    "INACTIVE_REASON" as inactive_reason,
    "DEATH_DATE" as death_date,
    "FIRST_FILE_DATE" as first_file_date,
    "LOCAL_AUTHORITY" as local_authority,
    "ENROLLED" as enrolled,
    "ENROLLED_DATE" as enrolled_date,
    "ONBOARDED" as onboarded,
    "ONBOARDED_DATE" as onboarded_date,
    "DAYS_ONBOARDED" as days_onboarded,
    "DISCHARGED" as discharged,
    "DISCHARGED_DATE" as discharged_date,
    "GENDER" as gender,
    "AGE_YEARS" as age_years,
    "IMD_DECILE" as imd_decile,
    "IS_CARE_HOME" as is_care_home,
    "ETHNICITY_GROUP" as ethnicity_group,
    "MOST_RECENT_NEL_ADMISSION_DATE" as most_recent_nel_admission_date,
    "DAYS_SINCE_NEL_ADMISSION" as days_since_nel_admission,
    "NEL_ADMISSIONS_2_YEARS" as nel_admissions_2_years,
    "BARNET_HOSPITAL_COUNT" as barnet_hospital_count,
    "RFL_COUNT" as rfl_count,
    "TOTAL_HIGH_RISK_CONDITIONS" as total_high_risk_conditions,
    "ALCOHOL_DEPENDENCE" as alcohol_dependence,
    "ATRIAL_FIBRILLATION" as atrial_fibrillation,
    "BRONCHIECTASIS" as bronchiectasis,
    "CEREBROVASCULAR_DISEASE" as cerebrovascular_disease,
    "CHRONIC_KIDNEY_DISEASE" as chronic_kidney_disease,
    "CHRONIC_LIVER_DISEASE" as chronic_liver_disease,
    "COPD" as copd,
    "CORONARY_HEART_DISEASE" as coronary_heart_disease,
    "DEMENTIA" as dementia,
    "END_STAGE_RENAL_FAILURE" as end_stage_renal_failure,
    "FRAILTY_FALLS" as frailty_falls,
    "HEART_FAILURE" as heart_failure,
    "HYPERTENSION" as hypertension,
    "LIVER_FAILURE" as liver_failure,
    "OSTEOPOROSIS" as osteoporosis,
    "PARKINSONS_DISEASE" as parkinsons_disease,
    "PERIPHERAL_VASCULAR_DISEASE" as peripheral_vascular_disease,
    "PULMONARY_HEART_DISEASE" as pulmonary_heart_disease,
    "RHEUMATOID_ARTHRITIS" as rheumatoid_arthritis,
    "SEVERE_INTERSTITIAL_LUNG_DISEASE" as severe_interstitial_lung_disease,
    "AGE_BAND" as age_band,
    "DAYS_BAND" as days_band,
    "MONTHS_ELIGIBLE" as months_eligible,
    "ETH_WHITE" as eth_white,
    "ETH_MIXED" as eth_mixed,
    "ETH_ASIAN" as eth_asian,
    "ETH_BLACK" as eth_black,
    "ETH_OTHER" as eth_other,
    "_GROUP" as group_value,
    "PROPENSITY_SCORE" as propensity_score,
    "MATCH_ID" as match_id,
    "MATCH_DISTANCE" as match_distance,
    "IS_OPTED_IN" as is_opted_in,
    "FILE_DATE" as file_date,
    "SOURCE_FILE" as source_file,
    "LOADED_AT" as loaded_at
from {{ source('myria', 'MATCHED_PATIENTS') }}
