{{
    config(
        description="Raw layer (Project Myria (BEVC) canonical inputs - Doccla enrolled patients and the propensity-matched evaluation population. One row per patient per file; FILE_DATE identifies the upload. Loaded by MYRIA.LOAD_NEW_FILES().). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE__NCL.MYRIA.RFL_SUBMISSION_PATIENTS \ndbt: source(''myria'', ''RFL_SUBMISSION_PATIENTS'') \nColumns:\n  FILE_DATE -> file_date\n  SOURCE_FILE -> source_file\n  LOADED_AT -> loaded_at\n  HEX_ID -> hex_id\n  HOSPITAL_NUMBER -> hospital_number\n  DATA_SOURCE_REFRESH_DATE -> data_source_refresh_date\n  GP_CODE -> gp_code\n  GP_PRACTICE_NAME -> gp_practice_name\n  LOCAL_AUTHORITY -> local_authority\n  BH_NEL_ADMISSIONS_1_YEAR -> bh_nel_admissions_1_year\n  RFL_ADMISSIONS_1_YEAR -> rfl_admissions_1_year\n  NEL_ADMISSIONS_2_YEARS -> nel_admissions_2_years\n  ALCOHOL_DEPENDENCE -> alcohol_dependence\n  ATRIAL_FIBRILLATION -> atrial_fibrillation\n  BRONCHIECTASIS -> bronchiectasis\n  CEREBROVASCULAR_DISEASE -> cerebrovascular_disease\n  CHRONIC_KIDNEY_DISEASE -> chronic_kidney_disease\n  CHRONIC_LIVER_DISEASE -> chronic_liver_disease\n  COPD -> copd\n  CORONARY_HEART_DISEASE -> coronary_heart_disease\n  DEMENTIA -> dementia\n  END_STAGE_RENAL_FAILURE -> end_stage_renal_failure\n  FRAILTY_FALLS -> frailty_falls\n  HEART_FAILURE -> heart_failure\n  HYPERTENSION -> hypertension\n  LIVER_FAILURE -> liver_failure\n  OSTEOPOROSIS -> osteoporosis\n  PARKINSONS_DISEASE -> parkinsons_disease\n  PERIPHERAL_VASCULAR_DISEASE -> peripheral_vascular_disease\n  PULMONARY_HEART_DISEASE -> pulmonary_heart_disease\n  RHEUMATOID_ARTHRITIS -> rheumatoid_arthritis\n  SEVERE_INTERSTITIAL_LUNG_DISEASE -> severe_interstitial_lung_disease\n  TOTAL_HIGH_RISK_CONDITIONS -> total_high_risk_conditions\n  MOST_RECENT_NEL_ADMISSION_DATE -> most_recent_nel_admission_date\n  IS_ACTIVE -> is_active\n  NCL_BOROUGH_REGISTERED -> ncl_borough_registered\n  BOROUGH_RESIDENT -> borough_resident\n  IS_DECEASED -> is_deceased\n  DEATH_DATE_APPROX -> death_date_approx\n  IS_ON_PDS -> is_on_pds\n  IS_MATCH_OLIDS -> is_match_olids\n  INACTIVE_REASON -> inactive_reason\n  IS_ON_PALLIATIVE_CARE_REGISTER -> is_on_palliative_care_register\n  BH_DISCHARGE_LAST_12M -> bh_discharge_last_12_m"
    )
}}
select
    "FILE_DATE" as file_date,
    "SOURCE_FILE" as source_file,
    "LOADED_AT" as loaded_at,
    "HEX_ID" as hex_id,
    "HOSPITAL_NUMBER" as hospital_number,
    "DATA_SOURCE_REFRESH_DATE" as data_source_refresh_date,
    "GP_CODE" as gp_code,
    "GP_PRACTICE_NAME" as gp_practice_name,
    "LOCAL_AUTHORITY" as local_authority,
    "BH_NEL_ADMISSIONS_1_YEAR" as bh_nel_admissions_1_year,
    "RFL_ADMISSIONS_1_YEAR" as rfl_admissions_1_year,
    "NEL_ADMISSIONS_2_YEARS" as nel_admissions_2_years,
    "ALCOHOL_DEPENDENCE" as alcohol_dependence,
    "ATRIAL_FIBRILLATION" as atrial_fibrillation,
    "BRONCHIECTASIS" as bronchiectasis,
    "CEREBROVASCULAR_DISEASE" as cerebrovascular_disease,
    "CHRONIC_KIDNEY_DISEASE" as chronic_kidney_disease,
    "CHRONIC_LIVER_DISEASE" as chronic_liver_disease,
    "COPD" as copd,
    "CORONARY_HEART_DISEASE" as coronary_heart_disease,
    "DEMENTIA" as dementia,
    "END_STAGE_RENAL_FAILURE" as end_stage_renal_failure,
    "FRAILTY_FALLS" as frailty_falls,
    "HEART_FAILURE" as heart_failure,
    "HYPERTENSION" as hypertension,
    "LIVER_FAILURE" as liver_failure,
    "OSTEOPOROSIS" as osteoporosis,
    "PARKINSONS_DISEASE" as parkinsons_disease,
    "PERIPHERAL_VASCULAR_DISEASE" as peripheral_vascular_disease,
    "PULMONARY_HEART_DISEASE" as pulmonary_heart_disease,
    "RHEUMATOID_ARTHRITIS" as rheumatoid_arthritis,
    "SEVERE_INTERSTITIAL_LUNG_DISEASE" as severe_interstitial_lung_disease,
    "TOTAL_HIGH_RISK_CONDITIONS" as total_high_risk_conditions,
    "MOST_RECENT_NEL_ADMISSION_DATE" as most_recent_nel_admission_date,
    "IS_ACTIVE" as is_active,
    "NCL_BOROUGH_REGISTERED" as ncl_borough_registered,
    "BOROUGH_RESIDENT" as borough_resident,
    "IS_DECEASED" as is_deceased,
    "DEATH_DATE_APPROX" as death_date_approx,
    "IS_ON_PDS" as is_on_pds,
    "IS_MATCH_OLIDS" as is_match_olids,
    "INACTIVE_REASON" as inactive_reason,
    "IS_ON_PALLIATIVE_CARE_REGISTER" as is_on_palliative_care_register,
    "BH_DISCHARGE_LAST_12M" as bh_discharge_last_12_m
from {{ source('myria', 'RFL_SUBMISSION_PATIENTS') }}
