{{ config(tags=['qadmissions', 'monthly-full']) }}

-- Canary for the QAdmissions SQL scoring path (qadmissions_predict).
--
-- Scores 36 synthetic rows through the registered model and returns any row
-- whose result differs from the result the qadmission_review scoring code
-- gives: a different ok flag, a score more than 1e-05 apart, or different
-- error text. Each row changes one input from a baseline, so a wrongly mapped
-- input, another model version or a change to the inputs on either side
-- fails the test. All values are made up.
--
-- Generated by qadmission_review/prototype/option_d/generate_canary_test.py.
-- Regenerate it rather than editing the values by hand.

with canary (
    case_id, description, sex, age, alcohol_cat6, b_af, b_ccf, b_anticoagulant, b_antidepressant, b_antipsychotic, b_anycancer, b_asthmacopd, b_corticosteroids, b_cvd, b_epilepsy, b_falls, b_liverpancreas, b_malabsorption, b_manicschiz, b_nsaid, b_renal, b_type1, b_type2, b_vte, bmi, c_hb, ethrisk, hes_admitprior_cat, high_lft, high_platelet, sha1, smoke_cat, surv, town, expected_ok, expected_score_percent, expected_errors
) as (
    select * from values
        (1, 'baseline (example input)', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 9.09554246805393, NULL),
        (2, 'b_af true', 'female', 80, 0, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 11.794441337832307, NULL),
        (3, 'b_ccf true', 'female', 80, 0, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 10.706534939724232, NULL),
        (4, 'b_anticoagulant true', 'female', 80, 0, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 10.562155416350905, NULL),
        (5, 'b_antidepressant true', 'female', 80, 0, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 11.681996378871073, NULL),
        (6, 'b_antipsychotic true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 11.532051926473997, NULL),
        (7, 'b_anycancer true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 12.041353231816865, NULL),
        (8, 'b_asthmacopd true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 10.823102101689841, NULL),
        (9, 'b_corticosteroids true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 13.290821035097222, NULL),
        (10, 'b_cvd true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 12.150046487088284, NULL),
        (11, 'b_epilepsy true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 11.805756662628086, NULL),
        (12, 'b_falls true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 11.372364377470456, NULL),
        (13, 'b_liverpancreas true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 10.877145810033117, NULL),
        (14, 'b_malabsorption true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 10.28822491454957, NULL),
        (15, 'b_manicschiz true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 11.161525962952023, NULL),
        (16, 'b_nsaid true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 9.092881466124215, NULL),
        (17, 'b_renal true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 12.163041531296138, NULL),
        (18, 'b_type1 true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 18.6713905948084, NULL),
        (19, 'b_type2 true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 11.25705120614363, NULL),
        (20, 'b_vte true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 10.805436725418305, NULL),
        (21, 'c_hb true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, TRUE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 11.622999831186853, NULL),
        (22, 'high_lft true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, TRUE, FALSE, 5, 0, 1, 0.0, TRUE, 12.847308920422895, NULL),
        (23, 'high_platelet true', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, TRUE, 5, 0, 1, 0.0, TRUE, 11.510467585135075, NULL),
        (24, 'male', 'male', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 11.252503944606019, NULL),
        (25, 'age 60', 'female', 60, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 3.4639007648940123, NULL),
        (26, 'alcohol category 3', 'female', 80, 3, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 7.515832104913733, NULL),
        (27, 'bmi 31.5', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 31.5, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 9.57782442395072, NULL),
        (28, 'ethnicity group 2', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 2, 0, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 9.120261294149968, NULL),
        (29, '2 prior admissions', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 2, FALSE, FALSE, 5, 0, 1, 0.0, TRUE, 21.621441262119113, NULL),
        (30, 'health authority 3', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 3, 0, 1, 0.0, TRUE, 7.734115569922196, NULL),
        (31, 'smoking category 3', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 3, 1, 0.0, TRUE, 11.76861188452365, NULL),
        (32, '2-year horizon', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 2, 0.0, TRUE, 16.385635858162495, NULL),
        (33, 'Townsend 2.5', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 2.5, TRUE, 9.507655694947559, NULL),
        (34, 'bmi missing', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, NULL, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, FALSE, NULL, 'error: bmi must be in range (20.0,40.0)'),
        (35, 'alcohol category missing', 'female', 80, NULL, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 0.0, FALSE, NULL, 'error: alcohol_cat6 must be in range (0,5)'),
        (36, 'Townsend out of range', 'female', 80, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 23.0, FALSE, 1, 0, FALSE, FALSE, 5, 0, 1, 12.0, FALSE, NULL, 'error: town must be in range (-7.0,11.0)')
),

scored as (
    select
        case_id,
        description,
        expected_ok,
        expected_score_percent::float as expected_score_percent,
        expected_errors,
        {{ qadmissions_predict('c') }} as prediction
    from canary c
),

compared as (
    select
        case_id,
        description,
        expected_ok,
        prediction:"ok"::boolean as actual_ok,
        expected_score_percent,
        prediction:"score_percent"::float as actual_score_percent,
        expected_errors,
        prediction:"errors"::varchar as actual_errors
    from scored
)

select *
from compared
where actual_ok is distinct from expected_ok
   or (actual_score_percent is null) <> (expected_score_percent is null)
   or abs(actual_score_percent - expected_score_percent) > 1e-05
   or coalesce(actual_errors, '') <> coalesce(expected_errors, '')
