{{
    config(
        description="Raw layer (ServicesDataLocal canonical-named feeds, WNL footprint (SLAM contract monitoring)). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.SDL.MH \ndbt: source(''sdl_wnl'', ''MH'') \nColumns:\n  META_SK_ROW_ID -> meta_sk_row_id\n  META_FILE_ID -> meta_file_id\n  META_ROW_ID -> meta_row_id\n  META_BATCH_ID -> meta_batch_id\n  META_PARTITION_DATE -> meta_partition_date\n  META_PROVIDER_CODE -> meta_provider_code\n  META_RECIPIENT_CODE -> meta_recipient_code\n  META_VERSION_ID -> meta_version_id\n  ACTIVITY_MONTH -> activity_month\n  ADMITTED_FLAG -> admitted_flag\n  AGE_FLAG -> age_flag\n  ARRIVAL_DATE -> arrival_date\n  ATTENDANCE_DISPOSAL_DESC -> attendance_disposal_desc\n  ATTENDED_OR_DID_NOT_ATTEND_CODE -> attended_or_did_not_attend_code\n  BREACHES -> breaches\n  CAMHS_FLAG -> camhs_flag\n  CARE_CONTACT_DATE -> care_contact_date\n  CARE_CONTACT_IDENTIFIER -> care_contact_identifier\n  CARE_CONTACT_REFERRAL_ID -> care_contact_referral_id\n  CCG -> ccg\n  CCG_CODE -> ccg_code\n  CCG_DESCRIPTION -> ccg_description\n  CCG_GROUPS -> ccg_groups\n  CONSULTATION_MECHANISM_MENTAL_HEALTH_CODE -> consultation_mechanism_mental_health_code\n  DIAGNOSIS1_DESCRIPTION -> diagnosis1_description\n  DIAGNOSIS2_DESCRIPTION -> diagnosis2_description\n  DIAGNOSIS3_DESCRIPTION -> diagnosis3_description\n  DIAGNOSIS4_DESCRIPTION -> diagnosis4_description\n  DLP_BASELINE_FINANCIAL_MONTH -> dlp_baseline_financial_month\n  DLP_COMMISSIONER_CODE -> dlp_commissioner_code\n  DLP_FINANCIAL_MONTH -> dlp_financial_month\n  DLP_FINANCIAL_YEAR -> dlp_financial_year\n  DLP_FLEXOR_FREEZE -> dlp_flexor_freeze\n  DV_LSOA -> dv_lsoa\n  DV_PARTIAL_POST_CODE -> dv_partial_post_code\n  DV_RECIPIENT_CODE -> dv_recipient_code\n  DV_YEAROF_BIRTH -> dv_yearof_birth\n  ETHNIC_CATEGORY -> ethnic_category\n  EXTRACT_DATE -> extract_date\n  GENDER_IDENTITY_CODE -> gender_identity_code\n  GENERAL_MEDICAL_PRACTICE_CODE_PATIENT_REGISTRATION -> general_medical_practice_code_patient_registration\n  GENERAL_MEDICAL_PRACTICE_CODE_PATIENT_REGISTRATION_AT_POINT_OF_CONTACT -> general_medical_practice_code_patient_registration_at_point_of_contact\n  HOSPITAL_BED_TYPE_MENTAL_HEALTH_MENTAL_HEALTH_ADMITTED_PATIENT_CLASSIFICATION -> hospital_bed_type_mental_health_mental_health_admitted_patient_classification\n  HOSPITAL_PROVIDER_SPELL_IDENTIFIER -> hospital_provider_spell_identifier\n  HOSPITAL_SITE -> hospital_site\n  LOCAL_PATIENT_IDENTIFIER -> local_patient_identifier\n  MRN -> mrn\n  ORGANISATION_IDENTIFIER_CODE_OF_COMMISSIONER -> organisation_identifier_code_of_commissioner\n  ORGANISATION_IDENTIFIER_CODE_OF_PROVIDER -> organisation_identifier_code_of_provider\n  PRESENTING_COMPLAINT -> presenting_complaint\n  REFERRAL_REQUEST_RECEIVED_DATE -> referral_request_received_date\n  SERVICE_GROUP -> service_group\n  SERVICE_OR_TEAM_TYPE -> service_or_team_type\n  SERVICE_REQUEST_IDENTIFER_REFERRAL_ID -> service_request_identifer_referral_id\n  SK_PATIENT_ID_NHS_NUMBER -> sk_patient_id_nhs_number\n  TEAM_CODE -> team_code\n  TEAM_NAME -> team_name\n  TOTAL_OCCUPIED_BED_DAYS_EXCLUDING_LEAVE -> total_occupied_bed_days_excluding_leave\n  WARD_CODE -> ward_code\n  WARD_END_DATE -> ward_end_date\n  WARD_NAME -> ward_name\n  WARD_START_DATE -> ward_start_date"
    )
}}
select
    "META_SK_ROW_ID" as meta_sk_row_id,
    "META_FILE_ID" as meta_file_id,
    "META_ROW_ID" as meta_row_id,
    "META_BATCH_ID" as meta_batch_id,
    "META_PARTITION_DATE" as meta_partition_date,
    "META_PROVIDER_CODE" as meta_provider_code,
    "META_RECIPIENT_CODE" as meta_recipient_code,
    "META_VERSION_ID" as meta_version_id,
    "ACTIVITY_MONTH" as activity_month,
    "ADMITTED_FLAG" as admitted_flag,
    "AGE_FLAG" as age_flag,
    "ARRIVAL_DATE" as arrival_date,
    "ATTENDANCE_DISPOSAL_DESC" as attendance_disposal_desc,
    "ATTENDED_OR_DID_NOT_ATTEND_CODE" as attended_or_did_not_attend_code,
    "BREACHES" as breaches,
    "CAMHS_FLAG" as camhs_flag,
    "CARE_CONTACT_DATE" as care_contact_date,
    "CARE_CONTACT_IDENTIFIER" as care_contact_identifier,
    "CARE_CONTACT_REFERRAL_ID" as care_contact_referral_id,
    "CCG" as ccg,
    "CCG_CODE" as ccg_code,
    "CCG_DESCRIPTION" as ccg_description,
    "CCG_GROUPS" as ccg_groups,
    "CONSULTATION_MECHANISM_MENTAL_HEALTH_CODE" as consultation_mechanism_mental_health_code,
    "DIAGNOSIS1_DESCRIPTION" as diagnosis1_description,
    "DIAGNOSIS2_DESCRIPTION" as diagnosis2_description,
    "DIAGNOSIS3_DESCRIPTION" as diagnosis3_description,
    "DIAGNOSIS4_DESCRIPTION" as diagnosis4_description,
    "DLP_BASELINE_FINANCIAL_MONTH" as dlp_baseline_financial_month,
    "DLP_COMMISSIONER_CODE" as dlp_commissioner_code,
    "DLP_FINANCIAL_MONTH" as dlp_financial_month,
    "DLP_FINANCIAL_YEAR" as dlp_financial_year,
    "DLP_FLEXOR_FREEZE" as dlp_flexor_freeze,
    "DV_LSOA" as dv_lsoa,
    "DV_PARTIAL_POST_CODE" as dv_partial_post_code,
    "DV_RECIPIENT_CODE" as dv_recipient_code,
    "DV_YEAROF_BIRTH" as dv_yearof_birth,
    "ETHNIC_CATEGORY" as ethnic_category,
    "EXTRACT_DATE" as extract_date,
    "GENDER_IDENTITY_CODE" as gender_identity_code,
    "GENERAL_MEDICAL_PRACTICE_CODE_PATIENT_REGISTRATION" as general_medical_practice_code_patient_registration,
    "GENERAL_MEDICAL_PRACTICE_CODE_PATIENT_REGISTRATION_AT_POINT_OF_CONTACT" as general_medical_practice_code_patient_registration_at_point_of_contact,
    "HOSPITAL_BED_TYPE_MENTAL_HEALTH_MENTAL_HEALTH_ADMITTED_PATIENT_CLASSIFICATION" as hospital_bed_type_mental_health_mental_health_admitted_patient_classification,
    "HOSPITAL_PROVIDER_SPELL_IDENTIFIER" as hospital_provider_spell_identifier,
    "HOSPITAL_SITE" as hospital_site,
    "LOCAL_PATIENT_IDENTIFIER" as local_patient_identifier,
    "MRN" as mrn,
    "ORGANISATION_IDENTIFIER_CODE_OF_COMMISSIONER" as organisation_identifier_code_of_commissioner,
    "ORGANISATION_IDENTIFIER_CODE_OF_PROVIDER" as organisation_identifier_code_of_provider,
    "PRESENTING_COMPLAINT" as presenting_complaint,
    "REFERRAL_REQUEST_RECEIVED_DATE" as referral_request_received_date,
    "SERVICE_GROUP" as service_group,
    "SERVICE_OR_TEAM_TYPE" as service_or_team_type,
    "SERVICE_REQUEST_IDENTIFER_REFERRAL_ID" as service_request_identifer_referral_id,
    "SK_PATIENT_ID_NHS_NUMBER" as sk_patient_id_nhs_number,
    "TEAM_CODE" as team_code,
    "TEAM_NAME" as team_name,
    "TOTAL_OCCUPIED_BED_DAYS_EXCLUDING_LEAVE" as total_occupied_bed_days_excluding_leave,
    "WARD_CODE" as ward_code,
    "WARD_END_DATE" as ward_end_date,
    "WARD_NAME" as ward_name,
    "WARD_START_DATE" as ward_start_date
from {{ source('sdl_wnl', 'MH') }}
