{{
    config(
        description="Raw layer (Primary care medications and prescribing data). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.EPD_PRIMARY_CARE.MedsV1 \ndbt: source(''epd_primary_care'', ''MedsV1'') \nColumns:\n  AgeBands -> age_bands\n  BSAPrescriptionID -> bsa_prescription_id\n  ChargeStatus -> charge_status\n  CostCentreLSOA -> cost_centre_lsoa\n  CostCentreODSCode -> cost_centre_ods_code\n  CostCentreSubType -> cost_centre_sub_type\n  CostCentreType -> cost_centre_type\n  DispensedCountryCode -> dispensed_country_code\n  DispensedPharmacyLSOA -> dispensed_pharmacy_lsoa\n  DispensedPharmacyODSCode -> dispensed_pharmacy_ods_code\n  DispensedPharmacyType -> dispensed_pharmacy_type\n  EPSPrescriptionID -> eps_prescription_id\n  EPSPrescriptionIndicator -> eps_prescription_indicator\n  ExemptionCode -> exemption_code\n  HighVolVaccineIndicator -> high_vol_vaccine_indicator\n  ItemActualCost -> item_actual_cost\n  ItemCount -> item_count\n  ItemID -> item_id\n  ItemNIC -> item_nic\n  MaternityExemptionFlag -> maternity_exemption_flag\n  dmicPseudoNHSNumber -> dmic_pseudo_nhs_number\n  NotDispensedIndicator -> not_dispensed_indicator\n  OutOfHoursIndicator -> out_of_hours_indicator\n  PaidACBSIndicator -> paid_acbs_indicator\n  PaidBNFCode -> paid_bnf_code\n  PaidBNFName -> paid_bnf_name\n  PaidCDIndicator -> paid_cd_indicator\n  PaidDisallowedReason -> paid_disallowed_reason\n  PaidDissallowedIndicator -> paid_dissallowed_indicator\n  PaidDrugStrength -> paid_drug_strength\n  PaidFlavourIndicator -> paid_flavour_indicator\n  PaidFormulation -> paid_formulation\n  PaidIndicator -> paid_indicator\n  PaidPADMIndicator -> paid_padm_indicator\n  PaidQuantity -> paid_quantity\n  PaidSpecContIndicator -> paid_spec_cont_indicator\n  PaidSupplierName -> paid_supplier_name\n  PaiddmdCode -> paiddmd_code\n  PatientAge -> patient_age\n  PatientCCG -> patient_ccg\n  PatientGPCCG -> patient_gpccg\n  PatientGPLA -> patient_gpla\n  PatientGPLSOA -> patient_gplsoa\n  PatientGPODS -> patient_gpods\n  PatientGender -> patient_gender\n  PatientLA -> patient_la\n  PatientLSOA -> patient_lsoa\n  PrescribedBNFCode -> prescribed_bnf_code\n  PrescribedBNFName -> prescribed_bnf_name\n  PrescribedCountryCode -> prescribed_country_code\n  PrescribedFormulation -> prescribed_formulation\n  PrescribedMedicineStrength -> prescribed_medicine_strength\n  PrescribedQuantity -> prescribed_quantity\n  PrescribedSupplierName -> prescribed_supplier_name\n  PrescribeddmdCode -> prescribeddmd_code\n  PrescriberID -> prescriber_id\n  PrescriberType -> prescriber_type\n  PrivatePrescriptionIndicator -> private_prescription_indicator\n  ProcessedPeriod -> processed_period\n  ProcessingPeriodDate -> processing_period_date\n  dmicImportLogId -> dmic_import_log_id\n  dmicCostCentreODSCCGCode -> dmic_cost_centre_odsccg_code\n  dmicCostCentreLSOACCGCode -> dmic_cost_centre_lsoaccg_code\n  dmicDispensedPharmacyLSOACCGCode -> dmic_dispensed_pharmacy_lsoaccg_code\n  dmicSystemId -> dmic_system_id\n  dmicDateAdded -> dmic_date_added\n  dmicRecordHash -> dmic_record_hash\n  dmicProcessedPeriod -> dmic_processed_period\n  UniqSubmissionId -> uniq_submission_id"
    )
}}
select
    "AgeBands" as age_bands,
    "BSAPrescriptionID" as bsa_prescription_id,
    "ChargeStatus" as charge_status,
    "CostCentreLSOA" as cost_centre_lsoa,
    "CostCentreODSCode" as cost_centre_ods_code,
    "CostCentreSubType" as cost_centre_sub_type,
    "CostCentreType" as cost_centre_type,
    "DispensedCountryCode" as dispensed_country_code,
    "DispensedPharmacyLSOA" as dispensed_pharmacy_lsoa,
    "DispensedPharmacyODSCode" as dispensed_pharmacy_ods_code,
    "DispensedPharmacyType" as dispensed_pharmacy_type,
    "EPSPrescriptionID" as eps_prescription_id,
    "EPSPrescriptionIndicator" as eps_prescription_indicator,
    "ExemptionCode" as exemption_code,
    "HighVolVaccineIndicator" as high_vol_vaccine_indicator,
    "ItemActualCost" as item_actual_cost,
    "ItemCount" as item_count,
    "ItemID" as item_id,
    "ItemNIC" as item_nic,
    "MaternityExemptionFlag" as maternity_exemption_flag,
    "dmicPseudoNHSNumber" as dmic_pseudo_nhs_number,
    "NotDispensedIndicator" as not_dispensed_indicator,
    "OutOfHoursIndicator" as out_of_hours_indicator,
    "PaidACBSIndicator" as paid_acbs_indicator,
    "PaidBNFCode" as paid_bnf_code,
    "PaidBNFName" as paid_bnf_name,
    "PaidCDIndicator" as paid_cd_indicator,
    "PaidDisallowedReason" as paid_disallowed_reason,
    "PaidDissallowedIndicator" as paid_dissallowed_indicator,
    "PaidDrugStrength" as paid_drug_strength,
    "PaidFlavourIndicator" as paid_flavour_indicator,
    "PaidFormulation" as paid_formulation,
    "PaidIndicator" as paid_indicator,
    "PaidPADMIndicator" as paid_padm_indicator,
    "PaidQuantity" as paid_quantity,
    "PaidSpecContIndicator" as paid_spec_cont_indicator,
    "PaidSupplierName" as paid_supplier_name,
    "PaiddmdCode" as paiddmd_code,
    "PatientAge" as patient_age,
    "PatientCCG" as patient_ccg,
    "PatientGPCCG" as patient_gpccg,
    "PatientGPLA" as patient_gpla,
    "PatientGPLSOA" as patient_gplsoa,
    "PatientGPODS" as patient_gpods,
    "PatientGender" as patient_gender,
    "PatientLA" as patient_la,
    "PatientLSOA" as patient_lsoa,
    "PrescribedBNFCode" as prescribed_bnf_code,
    "PrescribedBNFName" as prescribed_bnf_name,
    "PrescribedCountryCode" as prescribed_country_code,
    "PrescribedFormulation" as prescribed_formulation,
    "PrescribedMedicineStrength" as prescribed_medicine_strength,
    "PrescribedQuantity" as prescribed_quantity,
    "PrescribedSupplierName" as prescribed_supplier_name,
    "PrescribeddmdCode" as prescribeddmd_code,
    "PrescriberID" as prescriber_id,
    "PrescriberType" as prescriber_type,
    "PrivatePrescriptionIndicator" as private_prescription_indicator,
    "ProcessedPeriod" as processed_period,
    "ProcessingPeriodDate" as processing_period_date,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicCostCentreODSCCGCode" as dmic_cost_centre_odsccg_code,
    "dmicCostCentreLSOACCGCode" as dmic_cost_centre_lsoaccg_code,
    "dmicDispensedPharmacyLSOACCGCode" as dmic_dispensed_pharmacy_lsoaccg_code,
    "dmicSystemId" as dmic_system_id,
    "dmicDateAdded" as dmic_date_added,
    "dmicRecordHash" as dmic_record_hash,
    "dmicProcessedPeriod" as dmic_processed_period,
    "UniqSubmissionId" as uniq_submission_id
from {{ source('epd_primary_care', 'MedsV1') }}
