{{
    config(
        description="Raw layer (NHS Talking Therapies (IAPT) dataset). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.IAPT.IDS201CareContact \ndbt: source(''iapt'', ''IDS201CareContact'') \nColumns:\n  SK -> sk\n  CareContactId -> care_contact_id\n  ServiceRequestId -> service_request_id\n  CareContDate -> care_cont_date\n  CareContTime -> care_cont_time\n  OrgIDComm -> org_id_comm\n  PlannedCareContIndicator -> planned_care_cont_indicator\n  AttendOrDNACode -> attend_or_dna_code\n  Cancellation -> cancellation\n  ClinContDurOfCareCont -> clin_cont_dur_of_care_cont\n  IAPTLTCServiceInd -> iaptltc_service_ind\n  AppType -> app_type\n  ConsMediumUsed -> cons_medium_used\n  ConsMechanism -> cons_mechanism\n  IntEnabledTherProg -> int_enabled_ther_prog\n  CareContPatientTherMode -> care_cont_patient_ther_mode\n  NumGroupTherParticipants -> num_group_ther_participants\n  NumGroupTherFacilitators -> num_group_ther_facilitators\n  PsychMed -> psych_med\n  ActLocTypeCode -> act_loc_type_code\n  SiteIDOfTreat -> site_id_of_treat\n  LanguageCodeTreat -> language_code_treat\n  InterpreterPresentInd -> interpreter_present_ind\n  EFFECTIVE_FROM -> effective_from\n  RecordNumber -> record_number\n  UniqueID_IDS201 -> unique_id_ids201\n  OrgID_Provider -> org_id_provider\n  Person_ID -> person_id\n  UniqueSubmissionID -> unique_submission_id\n  Unique_ServiceRequestID -> unique_service_request_id\n  Unique_CareContactID -> unique_care_contact_id\n  Age_CareContact_Date -> age_care_contact_date\n  DistanceFromHome_ContactLocation -> distance_from_home_contact_location\n  Time_Referral_to_CareContact -> time_referral_to_care_contact\n  Unique_MonthID -> unique_month_id\n  PathwayID -> pathway_id\n  dmicImportLogId -> dmic_import_log_id\n  dmicSystemId -> dmic_system_id\n  dmicCCGCode -> dmic_ccg_code\n  dmicDateAdded -> dmic_date_added\n  dmIcbCommissioner -> dm_icb_commissioner\n  dmSubIcbCommissioner -> dm_sub_icb_commissioner\n  dmCommissionerDerivationReason -> dm_commissioner_derivation_reason"
    )
}}
select
    "SK" as sk,
    "CareContactId" as care_contact_id,
    "ServiceRequestId" as service_request_id,
    "CareContDate" as care_cont_date,
    "CareContTime" as care_cont_time,
    "OrgIDComm" as org_id_comm,
    "PlannedCareContIndicator" as planned_care_cont_indicator,
    "AttendOrDNACode" as attend_or_dna_code,
    "Cancellation" as cancellation,
    "ClinContDurOfCareCont" as clin_cont_dur_of_care_cont,
    "IAPTLTCServiceInd" as iaptltc_service_ind,
    "AppType" as app_type,
    "ConsMediumUsed" as cons_medium_used,
    "ConsMechanism" as cons_mechanism,
    "IntEnabledTherProg" as int_enabled_ther_prog,
    "CareContPatientTherMode" as care_cont_patient_ther_mode,
    "NumGroupTherParticipants" as num_group_ther_participants,
    "NumGroupTherFacilitators" as num_group_ther_facilitators,
    "PsychMed" as psych_med,
    "ActLocTypeCode" as act_loc_type_code,
    "SiteIDOfTreat" as site_id_of_treat,
    "LanguageCodeTreat" as language_code_treat,
    "InterpreterPresentInd" as interpreter_present_ind,
    "EFFECTIVE_FROM" as effective_from,
    "RecordNumber" as record_number,
    "UniqueID_IDS201" as unique_id_ids201,
    "OrgID_Provider" as org_id_provider,
    "Person_ID" as person_id,
    "UniqueSubmissionID" as unique_submission_id,
    "Unique_ServiceRequestID" as unique_service_request_id,
    "Unique_CareContactID" as unique_care_contact_id,
    "Age_CareContact_Date" as age_care_contact_date,
    "DistanceFromHome_ContactLocation" as distance_from_home_contact_location,
    "Time_Referral_to_CareContact" as time_referral_to_care_contact,
    "Unique_MonthID" as unique_month_id,
    "PathwayID" as pathway_id,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "dmIcbCommissioner" as dm_icb_commissioner,
    "dmSubIcbCommissioner" as dm_sub_icb_commissioner,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason
from {{ source('iapt', 'IDS201CareContact') }}
