{{
    config(
        description="Raw layer (Rapid Cancer Registration Dataset (RCRD)). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.RCRD.NDR001RapidRegistration \ndbt: source(''rcrd'', ''NDR001RapidRegistration'') \nColumns:\n  SK -> sk\n  Snapshot -> snapshot\n  INDIVIDUAL_ID -> individual_id\n  PATIENT_ID -> patient_id\n  NHS_NUMBER Pseudo -> nhs_number_pseudo\n  TUMOUR_AVP_ID -> tumour_avp_id\n  DIAGNOSISDATE -> diagnosisdate\n  TUMOUR_SITE -> tumour_site\n  CANCER_GROUP -> cancer_group\n  GENDER -> gender\n  AGE -> age\n  STAGE -> stage\n  ETHNICCATEGORY -> ethniccategory\n  FINAL_ROUTE -> final_route\n  IMD_QUINTILE -> imd_quintile\n  IMD_YEAR -> imd_year\n  CHRL_TOT_27_03 -> chrl_tot_27_03\n  TUMOUR_MORPHOLOGY -> tumour_morphology\n  TUMOUR_PERFORMANCESTATUS -> tumour_performancestatus\n  BASISOFDIAGNOSIS -> basisofdiagnosis\n  CCG_CODE -> ccg_code\n  CCG_NAME -> ccg_name\n  TRUST_CODE -> trust_code\n  STP_CODE -> stp_code\n  STP_NAME -> stp_name\n  CANALLIANCE_CODE -> canalliance_code\n  CANALLIANCE_NAME -> canalliance_name\n  NHS_REGION_CODE -> nhs_region_code\n  NHS_REGION_NAME -> nhs_region_name\n  ENG_LOC_CODE -> eng_loc_code\n  ENG_LOC_NAME -> eng_loc_name\n  ICB_CODE -> icb_code\n  ICB_NAME -> icb_name\n  GEOG_BOUNDARY_YEAR -> geog_boundary_year\n  SOURCE -> source\n  dmicImportLogId -> dmic_import_log_id\n  NDR001_ID -> ndr001_id\n  UniqSubmissionId -> uniq_submission_id\n  Unique_MonthId -> unique_month_id\n  dmicSystemId -> dmic_system_id\n  dmicDateAdded -> dmic_date_added\n  dmPracticeCode -> dm_practice_code\n  dmIcbOfRegistration -> dm_icb_of_registration\n  dmSubIcbOfRegistration -> dm_sub_icb_of_registration\n  dmCCGCode -> dm_ccg_code\n  dmSTPCode -> dm_stp_code\n  dmCanAllianceCode -> dm_can_alliance_code\n  dmICBCode -> dm_icb_code\n  dmIcbCommissioner -> dm_icb_commissioner\n  dmSubIcbCommissioner -> dm_sub_icb_commissioner\n  dmIcbResidenceSubmitted -> dm_icb_residence_submitted\n  dmSubIcbResidenceSubmitted -> dm_sub_icb_residence_submitted\n  dmCommissionerDerivationReason -> dm_commissioner_derivation_reason\n  dmicRecordHash -> dmic_record_hash"
    )
}}
select
    "SK" as sk,
    "Snapshot" as snapshot,
    "INDIVIDUAL_ID" as individual_id,
    "PATIENT_ID" as patient_id,
    "NHS_NUMBER Pseudo" as nhs_number_pseudo,
    "TUMOUR_AVP_ID" as tumour_avp_id,
    "DIAGNOSISDATE" as diagnosisdate,
    "TUMOUR_SITE" as tumour_site,
    "CANCER_GROUP" as cancer_group,
    "GENDER" as gender,
    "AGE" as age,
    "STAGE" as stage,
    "ETHNICCATEGORY" as ethniccategory,
    "FINAL_ROUTE" as final_route,
    "IMD_QUINTILE" as imd_quintile,
    "IMD_YEAR" as imd_year,
    "CHRL_TOT_27_03" as chrl_tot_27_03,
    "TUMOUR_MORPHOLOGY" as tumour_morphology,
    "TUMOUR_PERFORMANCESTATUS" as tumour_performancestatus,
    "BASISOFDIAGNOSIS" as basisofdiagnosis,
    "CCG_CODE" as ccg_code,
    "CCG_NAME" as ccg_name,
    "TRUST_CODE" as trust_code,
    "STP_CODE" as stp_code,
    "STP_NAME" as stp_name,
    "CANALLIANCE_CODE" as canalliance_code,
    "CANALLIANCE_NAME" as canalliance_name,
    "NHS_REGION_CODE" as nhs_region_code,
    "NHS_REGION_NAME" as nhs_region_name,
    "ENG_LOC_CODE" as eng_loc_code,
    "ENG_LOC_NAME" as eng_loc_name,
    "ICB_CODE" as icb_code,
    "ICB_NAME" as icb_name,
    "GEOG_BOUNDARY_YEAR" as geog_boundary_year,
    "SOURCE" as source,
    "dmicImportLogId" as dmic_import_log_id,
    "NDR001_ID" as ndr001_id,
    "UniqSubmissionId" as uniq_submission_id,
    "Unique_MonthId" as unique_month_id,
    "dmicSystemId" as dmic_system_id,
    "dmicDateAdded" as dmic_date_added,
    "dmPracticeCode" as dm_practice_code,
    "dmIcbOfRegistration" as dm_icb_of_registration,
    "dmSubIcbOfRegistration" as dm_sub_icb_of_registration,
    "dmCCGCode" as dm_ccg_code,
    "dmSTPCode" as dm_stp_code,
    "dmCanAllianceCode" as dm_can_alliance_code,
    "dmICBCode" as dm_icb_code,
    "dmIcbCommissioner" as dm_icb_commissioner,
    "dmSubIcbCommissioner" as dm_sub_icb_commissioner,
    "dmIcbResidenceSubmitted" as dm_icb_residence_submitted,
    "dmSubIcbResidenceSubmitted" as dm_sub_icb_residence_submitted,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason,
    "dmicRecordHash" as dmic_record_hash
from {{ source('rcrd', 'NDR001RapidRegistration') }}
