{{
    config(
        description="Raw layer (SUS Monthly emergency care attendances and activity). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.SUS_AE.EncounterDetail \ndbt: source(''sus_ae_monthly'', ''EncounterDetail'') \nColumns:\n  SK_EncounterID -> sk_encounter_id\n  StartDate -> start_date\n  EndDate -> end_date\n  SK_ArrivalModeID -> sk_arrival_mode_id\n  SK_AttendanceCategoryID -> sk_attendance_category_id\n  SK_AttendanceDisposalID -> sk_attendance_disposal_id\n  SK_IncidentLocationTypeID -> sk_incident_location_type_id\n  SK_SourceOfReferralID -> sk_source_of_referral_id\n  InitialAssessmentTime -> initial_assessment_time\n  TreatmentTime -> treatment_time\n  AttendanceConclusionTime -> attendance_conclusion_time\n  SK_AandEDepartmentNameID -> sk_aand_edepartment_name_id\n  PrimaryInvestigation -> primary_investigation\n  PrimaryDiagnosis -> primary_diagnosis\n  PrimaryTreatment -> primary_treatment\n  DiagnosisSchemeICD -> diagnosis_scheme_icd\n  PrimaryDiagnosisICD -> primary_diagnosis_icd\n  DiagnosisSchemeRead -> diagnosis_scheme_read\n  PrimaryDiagnosisRead -> primary_diagnosis_read\n  DiagType -> diag_type\n  InvestigationType -> investigation_type\n  TreatmentType -> treatment_type\n  SK_ServiceProviderID -> sk_service_provider_id\n  SK_PatientID -> sk_patient_id\n  SK_StaffID -> sk_staff_id\n  EncounterStartDateTime -> encounter_start_date_time\n  EncounterEndDateTime -> encounter_end_date_time\n  SK_CommissionerID -> sk_commissioner_id\n  Patient_group -> patient_group\n  HRG4_Code -> hrg4_code\n  DeleteEncounter -> delete_encounter\n  SK_AgeBandID -> sk_age_band_id\n  SK_Commissioner_PCTID -> sk_commissioner_pctid\n  Staff_Member_Code -> staff_member_code\n  Unique_CDS_Identifier -> unique_cds_identifier\n  SK_DepartmentTypeID -> sk_department_type_id\n  PASHospitalNumber -> pas_hospital_number\n  COMMISSIONER_SERIAL_NO -> commissioner_serial_no\n  PROVIDER_REFERENCE_NO -> provider_reference_no\n  AGREEMENT_LINE_NO -> agreement_line_no\n  Local_Site_Code -> local_site_code\n  AE_Attendance_No -> ae_attendance_no\n  SK_Org_CommissionerID -> sk_org_commissioner_id\n  SK_Org_ServiceProviderID -> sk_org_service_provider_id\n  PbROrSEM -> pb_ror_sem\n  CDS_Record_Type -> cds_record_type"
    )
}}
select
    "SK_EncounterID" as sk_encounter_id,
    "StartDate" as start_date,
    "EndDate" as end_date,
    "SK_ArrivalModeID" as sk_arrival_mode_id,
    "SK_AttendanceCategoryID" as sk_attendance_category_id,
    "SK_AttendanceDisposalID" as sk_attendance_disposal_id,
    "SK_IncidentLocationTypeID" as sk_incident_location_type_id,
    "SK_SourceOfReferralID" as sk_source_of_referral_id,
    "InitialAssessmentTime" as initial_assessment_time,
    "TreatmentTime" as treatment_time,
    "AttendanceConclusionTime" as attendance_conclusion_time,
    "SK_AandEDepartmentNameID" as sk_aand_edepartment_name_id,
    "PrimaryInvestigation" as primary_investigation,
    "PrimaryDiagnosis" as primary_diagnosis,
    "PrimaryTreatment" as primary_treatment,
    "DiagnosisSchemeICD" as diagnosis_scheme_icd,
    "PrimaryDiagnosisICD" as primary_diagnosis_icd,
    "DiagnosisSchemeRead" as diagnosis_scheme_read,
    "PrimaryDiagnosisRead" as primary_diagnosis_read,
    "DiagType" as diag_type,
    "InvestigationType" as investigation_type,
    "TreatmentType" as treatment_type,
    "SK_ServiceProviderID" as sk_service_provider_id,
    "SK_PatientID" as sk_patient_id,
    "SK_StaffID" as sk_staff_id,
    "EncounterStartDateTime" as encounter_start_date_time,
    "EncounterEndDateTime" as encounter_end_date_time,
    "SK_CommissionerID" as sk_commissioner_id,
    "Patient_group" as patient_group,
    "HRG4_Code" as hrg4_code,
    "DeleteEncounter" as delete_encounter,
    "SK_AgeBandID" as sk_age_band_id,
    "SK_Commissioner_PCTID" as sk_commissioner_pctid,
    "Staff_Member_Code" as staff_member_code,
    "Unique_CDS_Identifier" as unique_cds_identifier,
    "SK_DepartmentTypeID" as sk_department_type_id,
    "PASHospitalNumber" as pas_hospital_number,
    "COMMISSIONER_SERIAL_NO" as commissioner_serial_no,
    "PROVIDER_REFERENCE_NO" as provider_reference_no,
    "AGREEMENT_LINE_NO" as agreement_line_no,
    "Local_Site_Code" as local_site_code,
    "AE_Attendance_No" as ae_attendance_no,
    "SK_Org_CommissionerID" as sk_org_commissioner_id,
    "SK_Org_ServiceProviderID" as sk_org_service_provider_id,
    "PbROrSEM" as pb_ror_sem,
    "CDS_Record_Type" as cds_record_type
from {{ source('sus_ae_monthly', 'EncounterDetail') }}
