{{
    config(
        description="Raw layer (NHS Talking Therapies (IAPT) dataset). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.IAPT.IDS001MPI \ndbt: source(''iapt'', ''IDS001MPI'') \nColumns:\n  SK -> sk\n  LocalPatientId -> local_patient_id\n  OrgIDLocalPatientId -> org_id_local_patient_id\n  OrgIDResidenceResp -> org_id_residence_resp\n  NHSNumberStatus -> nhs_number_status\n  PersonBirthDate Pseudo -> person_birth_date_pseudo\n  Postcode Pseudo -> postcode_pseudo\n  Gender -> gender\n  GenderIdentity -> gender_identity\n  GenderIdentitySameAtBirth -> gender_identity_same_at_birth\n  EthnicCategory -> ethnic_category\n  EthnicCategory2021 -> ethnic_category2021\n  ExBAFIndicator -> ex_baf_indicator\n  LanguageCodePreferred -> language_code_preferred\n  EduEstabTypeIAPT -> edu_estab_type_iapt\n  EFFECTIVE_FROM -> effective_from\n  RecordNumber -> record_number\n  UniqueID_IDS001 -> unique_id_ids001\n  OrgID_Provider -> org_id_provider\n  OrgID_CCG_Residence -> org_id_ccg_residence\n  OrgIDSubICBLocResidence -> org_id_sub_icb_loc_residence\n  OrgIDICBRes -> org_idicb_res\n  Person_ID -> person_id\n  UniqueSubmissionID -> unique_submission_id\n  Age_RP_StartDate -> age_rp_start_date\n  Age_RP_EndDate -> age_rp_end_date\n  Postcode_District -> postcode_district\n  Postcode_Default Pseudo -> postcode_default_pseudo\n  ValidPostcode_Flag -> valid_postcode_flag\n  LSOA -> lsoa\n  Census_Year -> census_year\n  LocalAuthority -> local_authority\n  County -> county\n  ElectoralWard -> electoral_ward\n  Unique_MonthID -> unique_month_id\n  Validated_EthnicCategory -> validated_ethnic_category\n  MostRecentRecordRP_Patient -> most_recent_record_rp_patient\n  RecordStartDate -> record_start_date\n  RecordEndDate -> record_end_date\n  IndicesOfDeprivationDecile -> indices_of_deprivation_decile\n  IndicesOfDeprivationQuartile -> indices_of_deprivation_quartile\n  IMD_YEAR -> imd_year\n  dmicImportLogId -> dmic_import_log_id\n  dmicEthnicCategoryGroup -> dmic_ethnic_category_group\n  dmicSystemId -> dmic_system_id\n  dmicCCGCode -> dmic_ccg_code\n  dmicDateAdded -> dmic_date_added\n  Unique_LocalPatientId -> unique_local_patient_id\n  dmIcbResidenceSubmitted -> dm_icb_residence_submitted\n  dmSubIcbResidenceSubmitted -> dm_sub_icb_residence_submitted\n  dmCommissionerDerivationReason -> dm_commissioner_derivation_reason"
    )
}}
select
    "SK" as sk,
    "LocalPatientId" as local_patient_id,
    "OrgIDLocalPatientId" as org_id_local_patient_id,
    "OrgIDResidenceResp" as org_id_residence_resp,
    "NHSNumberStatus" as nhs_number_status,
    "PersonBirthDate Pseudo" as person_birth_date_pseudo,
    "Postcode Pseudo" as postcode_pseudo,
    "Gender" as gender,
    "GenderIdentity" as gender_identity,
    "GenderIdentitySameAtBirth" as gender_identity_same_at_birth,
    "EthnicCategory" as ethnic_category,
    "EthnicCategory2021" as ethnic_category2021,
    "ExBAFIndicator" as ex_baf_indicator,
    "LanguageCodePreferred" as language_code_preferred,
    "EduEstabTypeIAPT" as edu_estab_type_iapt,
    "EFFECTIVE_FROM" as effective_from,
    "RecordNumber" as record_number,
    "UniqueID_IDS001" as unique_id_ids001,
    "OrgID_Provider" as org_id_provider,
    "OrgID_CCG_Residence" as org_id_ccg_residence,
    "OrgIDSubICBLocResidence" as org_id_sub_icb_loc_residence,
    "OrgIDICBRes" as org_idicb_res,
    "Person_ID" as person_id,
    "UniqueSubmissionID" as unique_submission_id,
    "Age_RP_StartDate" as age_rp_start_date,
    "Age_RP_EndDate" as age_rp_end_date,
    "Postcode_District" as postcode_district,
    "Postcode_Default Pseudo" as postcode_default_pseudo,
    "ValidPostcode_Flag" as valid_postcode_flag,
    "LSOA" as lsoa,
    "Census_Year" as census_year,
    "LocalAuthority" as local_authority,
    "County" as county,
    "ElectoralWard" as electoral_ward,
    "Unique_MonthID" as unique_month_id,
    "Validated_EthnicCategory" as validated_ethnic_category,
    "MostRecentRecordRP_Patient" as most_recent_record_rp_patient,
    "RecordStartDate" as record_start_date,
    "RecordEndDate" as record_end_date,
    "IndicesOfDeprivationDecile" as indices_of_deprivation_decile,
    "IndicesOfDeprivationQuartile" as indices_of_deprivation_quartile,
    "IMD_YEAR" as imd_year,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicEthnicCategoryGroup" as dmic_ethnic_category_group,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "Unique_LocalPatientId" as unique_local_patient_id,
    "dmIcbResidenceSubmitted" as dm_icb_residence_submitted,
    "dmSubIcbResidenceSubmitted" as dm_sub_icb_residence_submitted,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason
from {{ source('iapt', 'IDS001MPI') }}
