select
    healthcare_event_id,
    event_type,
    person_id,
    patient_id,
    -- The stable key is already canonical text. TRIM prevents partition pruning here.
    nullif(sk_patient_id::varchar, '1') as sk_patient_id,
    event_at,
    event_date,
    event_time_precision,
    event_time_basis,
    source_record_type,
    source_record_id,
    appointment_id,
    clinical_record_id,
    event_code,
    event_code_name,
    event_coding_system,
    source_status_code,
    source_status_name,
    status_code,
    status_name,
    provider_organisation_id,
    publisher_organisation_id,
    publisher_organisation_code,
    source_extraction_date,
    provider_organisation_code,
    provider_code_authority,
    provider_organisation_name,
    publisher_organisation_name
from {{ ref('raw_olids_healthcare_event') }}
