{% macro nice_myocardial_infarction_union(reference='current') %}
SELECT
    person_id,
    indicator_id,
    indicator_name,
    reporting_date,
    measurement_period_start,
    age,
    condition_name,
    {{ nice_practice_columns(none, reference) }},
    earliest_mi_date,
    latest_mi_date,
    latest_mi_in_financial_year_date,
    first_lvsd_date,
    has_lvsd,
    has_ace_inhibitor_intolerance,
    has_aspirin_intolerance,
    latest_aspirin_record_date,
    antiplatelet_chemical_count_in_period,
    latest_ace_inhibitor_order_date,
    latest_arb_order_date,
    latest_aspirin_order_date,
    latest_p2y12_order_date,
    latest_clopidogrel_order_date,
    latest_antiplatelet_order_date,
    latest_anticoagulant_order_date,
    latest_statin_order_date,
    latest_beta_blocker_order_date,
    is_ace_inhibitor_in_period,
    is_arb_in_period,
    is_aspirin_in_period,
    is_p2y12_in_period,
    is_clopidogrel_in_period,
    is_antiplatelet_in_period,
    is_anticoagulant_in_period,
    is_statin_in_period,
    is_beta_blocker_in_period,
    is_in_numerator_lenient,
    latest_record_date,
    is_in_denominator,
    is_in_numerator,
    indicator_status
FROM {{ ref('fct_person_myocardial_infarction_therapy_ind125' if reference == 'current' else 'fct_person_myocardial_infarction_therapy_ind125_by_month') }}

UNION ALL

SELECT
    person_id,
    indicator_id,
    indicator_name,
    reporting_date,
    measurement_period_start,
    age,
    condition_name,
    {{ nice_practice_columns(none, reference) }},
    earliest_mi_date,
    latest_mi_date,
    latest_mi_in_financial_year_date,
    first_lvsd_date,
    has_lvsd,
    has_ace_inhibitor_intolerance,
    has_aspirin_intolerance,
    latest_aspirin_record_date,
    NULL::NUMBER AS antiplatelet_chemical_count_in_period,
    latest_ace_inhibitor_order_date,
    latest_arb_order_date,
    latest_aspirin_order_date,
    latest_p2y12_order_date,
    latest_clopidogrel_order_date,
    latest_antiplatelet_order_date,
    latest_anticoagulant_order_date,
    latest_statin_order_date,
    latest_beta_blocker_order_date,
    is_ace_inhibitor_in_period,
    is_arb_in_period,
    is_aspirin_in_period,
    is_p2y12_in_period,
    is_clopidogrel_in_period,
    is_antiplatelet_in_period,
    is_anticoagulant_in_period,
    is_statin_in_period,
    is_beta_blocker_in_period,
    is_in_numerator_lenient,
    latest_record_date,
    is_in_denominator,
    is_in_numerator,
    indicator_status
FROM {{ ref('fct_person_myocardial_infarction_therapy_ind126' if reference == 'current' else 'fct_person_myocardial_infarction_therapy_ind126_by_month') }}
{% endmacro %}
