{{
    config(
        description="Raw layer (OLIDS stable layer - cleaned and filtered patient records). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.OLIDS.ENCOUNTER \ndbt: source(''olids'', ''ENCOUNTER'') \nColumns:\n  ID -> id\n  LDS_SOURCE_RECORD_ID -> lds_source_record_id\n  PATIENT_ID -> patient_id\n  PERSON_ID -> person_id\n  PUBLISHER_ORGANISATION_ID -> publisher_organisation_id\n  PROVIDER_ORGANISATION_ID -> provider_organisation_id\n  AUTHOR_ORGANISATION_ID -> author_organisation_id\n  EPISODE_OF_CARE_ID -> episode_of_care_id\n  APPOINTMENT_ID -> appointment_id\n  PRACTITIONER_ID -> practitioner_id\n  LOCATION -> location\n  ENCOUNTER_SOURCE_CONCEPT_ID -> encounter_source_concept_id\n  SOURCE_CODE -> source_code\n  SOURCE_DISPLAY -> source_display\n  SOURCE_SYSTEM -> source_system\n  MAPPED_CONCEPT_ID -> mapped_concept_id\n  MAPPED_CONCEPT_CODE -> mapped_concept_code\n  MAPPED_CONCEPT_DISPLAY -> mapped_concept_display\n  TARGET_SYSTEM -> target_system\n  CLINICAL_EFFECTIVE_DATE_PRECISION_SOURCE_CONCEPT_ID -> clinical_effective_date_precision_source_concept_id\n  DATE_PRECISION_SOURCE_CODE -> date_precision_source_code\n  DATE_PRECISION_SOURCE_DISPLAY -> date_precision_source_display\n  DATE_PRECISION_CODE -> date_precision_code\n  DATE_PRECISION_DISPLAY -> date_precision_display\n  CONSULTATION_TYPE -> consultation_type\n  CLINICAL_EFFECTIVE_DATE -> clinical_effective_date\n  DATE_RECORDED -> date_recorded\n  IS_CONFIDENTIAL -> is_confidential\n  AGE_AT_EVENT -> age_at_event\n  AGE_AT_EVENT_BABY -> age_at_event_baby\n  AGE_AT_EVENT_NEONATE -> age_at_event_neonate\n  TYPE -> type\n  SUBTYPE -> subtype\n  ADMISSION_METHOD -> admission_method\n  LDS_IS_DELETED -> lds_is_deleted\n  PUBLISHER_ORGANISATION_CODE -> publisher_organisation_code\n  CLINICAL_SYSTEM -> clinical_system\n  SOURCE_EXTRACTION_DATE -> source_extraction_date\n  LDS_TRANSFORM_DATETIME -> lds_transform_datetime"
    )
}}
select
    "ID" as id,
    "LDS_SOURCE_RECORD_ID" as lds_source_record_id,
    "PATIENT_ID" as patient_id,
    "PERSON_ID" as person_id,
    "PUBLISHER_ORGANISATION_ID" as publisher_organisation_id,
    "PROVIDER_ORGANISATION_ID" as provider_organisation_id,
    "AUTHOR_ORGANISATION_ID" as author_organisation_id,
    "EPISODE_OF_CARE_ID" as episode_of_care_id,
    "APPOINTMENT_ID" as appointment_id,
    "PRACTITIONER_ID" as practitioner_id,
    "LOCATION" as location,
    "ENCOUNTER_SOURCE_CONCEPT_ID" as encounter_source_concept_id,
    "SOURCE_CODE" as source_code,
    "SOURCE_DISPLAY" as source_display,
    "SOURCE_SYSTEM" as source_system,
    "MAPPED_CONCEPT_ID" as mapped_concept_id,
    "MAPPED_CONCEPT_CODE" as mapped_concept_code,
    "MAPPED_CONCEPT_DISPLAY" as mapped_concept_display,
    "TARGET_SYSTEM" as target_system,
    "CLINICAL_EFFECTIVE_DATE_PRECISION_SOURCE_CONCEPT_ID" as clinical_effective_date_precision_source_concept_id,
    "DATE_PRECISION_SOURCE_CODE" as date_precision_source_code,
    "DATE_PRECISION_SOURCE_DISPLAY" as date_precision_source_display,
    "DATE_PRECISION_CODE" as date_precision_code,
    "DATE_PRECISION_DISPLAY" as date_precision_display,
    "CONSULTATION_TYPE" as consultation_type,
    "CLINICAL_EFFECTIVE_DATE" as clinical_effective_date,
    "DATE_RECORDED" as date_recorded,
    "IS_CONFIDENTIAL" as is_confidential,
    "AGE_AT_EVENT" as age_at_event,
    "AGE_AT_EVENT_BABY" as age_at_event_baby,
    "AGE_AT_EVENT_NEONATE" as age_at_event_neonate,
    "TYPE" as type,
    "SUBTYPE" as subtype,
    "ADMISSION_METHOD" as admission_method,
    "LDS_IS_DELETED" as lds_is_deleted,
    "PUBLISHER_ORGANISATION_CODE" as publisher_organisation_code,
    "CLINICAL_SYSTEM" as clinical_system,
    "SOURCE_EXTRACTION_DATE" as source_extraction_date,
    "LDS_TRANSFORM_DATETIME" as lds_transform_datetime
from {{ source('olids', 'ENCOUNTER') }}
