{{
    config(
        description="Raw layer (OLIDS stable layer - cleaned and filtered patient records). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.OLIDS.REFERRAL_REQUEST \ndbt: source(''olids'', ''REFERRAL_REQUEST'') \nColumns:\n  ID -> id\n  LDS_SOURCE_RECORD_ID -> lds_source_record_id\n  PATIENT_ID -> patient_id\n  PERSON_ID -> person_id\n  PUBLISHER_ORGANISATION_ID -> publisher_organisation_id\n  AUTHOR_ORGANISATION_ID -> author_organisation_id\n  ENCOUNTER_ID -> encounter_id\n  PRACTITIONER_ID -> practitioner_id\n  UNIQUE_BOOKING_REFERENCE_NUMBER -> unique_booking_reference_number\n  CLINICAL_EFFECTIVE_DATE -> clinical_effective_date\n  CLINICAL_EFFECTIVE_DATE_PRECISION_SOURCE_CONCEPT_ID -> clinical_effective_date_precision_source_concept_id\n  DATE_PRECISION_SOURCE_CODE -> date_precision_source_code\n  DATE_PRECISION_SOURCE_DISPLAY -> date_precision_source_display\n  DATE_PRECISION_CODE -> date_precision_code\n  DATE_PRECISION_DISPLAY -> date_precision_display\n  REQUESTER_ORGANISATION_ID -> requester_organisation_id\n  RECIPIENT_ORGANISATION_ID -> recipient_organisation_id\n  REFERRAL_REQUEST_PRIORITY_SOURCE_CONCEPT_ID -> referral_request_priority_source_concept_id\n  REFERRAL_REQUEST_PRIORITY_SOURCE_CODE -> referral_request_priority_source_code\n  REFERRAL_REQUEST_PRIORITY_SOURCE_DISPLAY -> referral_request_priority_source_display\n  REFERRAL_REQUEST_PRIORITY_CODE -> referral_request_priority_code\n  REFERRAL_REQUEST_PRIORITY_DISPLAY -> referral_request_priority_display\n  REFERRAL_REQUEST_TYPE_SOURCE_CONCEPT_ID -> referral_request_type_source_concept_id\n  REFERRAL_REQUEST_TYPE_SOURCE_CODE -> referral_request_type_source_code\n  REFERRAL_REQUEST_TYPE_SOURCE_DISPLAY -> referral_request_type_source_display\n  REFERRAL_REQUEST_TYPE_CODE -> referral_request_type_code\n  REFERRAL_REQUEST_TYPE_DISPLAY -> referral_request_type_display\n  REFERRAL_REQUEST_SPECIALTY_SOURCE_CONCEPT_ID -> referral_request_specialty_source_concept_id\n  REFERRAL_REQUEST_SPECIALTY_SOURCE_CODE -> referral_request_specialty_source_code\n  REFERRAL_REQUEST_SPECIALTY_SOURCE_DISPLAY -> referral_request_specialty_source_display\n  REFERRAL_REQUEST_SPECIALTY_CODE -> referral_request_specialty_code\n  REFERRAL_REQUEST_SPECIALTY_DISPLAY -> referral_request_specialty_display\n  MODE -> mode\n  IS_OUTGOING_REFERRAL -> is_outgoing_referral\n  IS_REVIEW -> is_review\n  REFERRAL_REQUEST_SOURCE_CONCEPT_ID -> referral_request_source_concept_id\n  SOURCE_CODE -> source_code\n  SOURCE_DISPLAY -> source_display\n  SOURCE_SYSTEM -> source_system\n  MAPPED_CONCEPT_ID -> mapped_concept_id\n  MAPPED_CONCEPT_CODE -> mapped_concept_code\n  MAPPED_CONCEPT_DISPLAY -> mapped_concept_display\n  TARGET_SYSTEM -> target_system\n  AGE_AT_EVENT -> age_at_event\n  AGE_AT_EVENT_BABY -> age_at_event_baby\n  AGE_AT_EVENT_NEONATE -> age_at_event_neonate\n  RECORDED_DATETIME -> recorded_datetime\n  VALUE -> value\n  LDS_IS_DELETED -> lds_is_deleted\n  PUBLISHER_ORGANISATION_CODE -> publisher_organisation_code\n  CLINICAL_SYSTEM -> clinical_system\n  SOURCE_EXTRACTION_DATE -> source_extraction_date\n  LDS_TRANSFORM_DATETIME -> lds_transform_datetime\n  OBSERVATION_ID -> observation_id\n  PROVIDER_ORGANISATION_ID -> provider_organisation_id\n  REFERRAL_SNOMED_CODE -> referral_snomed_code\n  REFERRAL_SNOMED_NAME -> referral_snomed_name"
    )
}}
select
    "ID" as id,
    "LDS_SOURCE_RECORD_ID" as lds_source_record_id,
    "PATIENT_ID" as patient_id,
    "PERSON_ID" as person_id,
    "PUBLISHER_ORGANISATION_ID" as publisher_organisation_id,
    "AUTHOR_ORGANISATION_ID" as author_organisation_id,
    "ENCOUNTER_ID" as encounter_id,
    "PRACTITIONER_ID" as practitioner_id,
    "UNIQUE_BOOKING_REFERENCE_NUMBER" as unique_booking_reference_number,
    "CLINICAL_EFFECTIVE_DATE" as clinical_effective_date,
    "CLINICAL_EFFECTIVE_DATE_PRECISION_SOURCE_CONCEPT_ID" as clinical_effective_date_precision_source_concept_id,
    "DATE_PRECISION_SOURCE_CODE" as date_precision_source_code,
    "DATE_PRECISION_SOURCE_DISPLAY" as date_precision_source_display,
    "DATE_PRECISION_CODE" as date_precision_code,
    "DATE_PRECISION_DISPLAY" as date_precision_display,
    "REQUESTER_ORGANISATION_ID" as requester_organisation_id,
    "RECIPIENT_ORGANISATION_ID" as recipient_organisation_id,
    "REFERRAL_REQUEST_PRIORITY_SOURCE_CONCEPT_ID" as referral_request_priority_source_concept_id,
    "REFERRAL_REQUEST_PRIORITY_SOURCE_CODE" as referral_request_priority_source_code,
    "REFERRAL_REQUEST_PRIORITY_SOURCE_DISPLAY" as referral_request_priority_source_display,
    "REFERRAL_REQUEST_PRIORITY_CODE" as referral_request_priority_code,
    "REFERRAL_REQUEST_PRIORITY_DISPLAY" as referral_request_priority_display,
    "REFERRAL_REQUEST_TYPE_SOURCE_CONCEPT_ID" as referral_request_type_source_concept_id,
    "REFERRAL_REQUEST_TYPE_SOURCE_CODE" as referral_request_type_source_code,
    "REFERRAL_REQUEST_TYPE_SOURCE_DISPLAY" as referral_request_type_source_display,
    "REFERRAL_REQUEST_TYPE_CODE" as referral_request_type_code,
    "REFERRAL_REQUEST_TYPE_DISPLAY" as referral_request_type_display,
    "REFERRAL_REQUEST_SPECIALTY_SOURCE_CONCEPT_ID" as referral_request_specialty_source_concept_id,
    "REFERRAL_REQUEST_SPECIALTY_SOURCE_CODE" as referral_request_specialty_source_code,
    "REFERRAL_REQUEST_SPECIALTY_SOURCE_DISPLAY" as referral_request_specialty_source_display,
    "REFERRAL_REQUEST_SPECIALTY_CODE" as referral_request_specialty_code,
    "REFERRAL_REQUEST_SPECIALTY_DISPLAY" as referral_request_specialty_display,
    "MODE" as mode,
    "IS_OUTGOING_REFERRAL" as is_outgoing_referral,
    "IS_REVIEW" as is_review,
    "REFERRAL_REQUEST_SOURCE_CONCEPT_ID" as referral_request_source_concept_id,
    "SOURCE_CODE" as source_code,
    "SOURCE_DISPLAY" as source_display,
    "SOURCE_SYSTEM" as source_system,
    "MAPPED_CONCEPT_ID" as mapped_concept_id,
    "MAPPED_CONCEPT_CODE" as mapped_concept_code,
    "MAPPED_CONCEPT_DISPLAY" as mapped_concept_display,
    "TARGET_SYSTEM" as target_system,
    "AGE_AT_EVENT" as age_at_event,
    "AGE_AT_EVENT_BABY" as age_at_event_baby,
    "AGE_AT_EVENT_NEONATE" as age_at_event_neonate,
    "RECORDED_DATETIME" as recorded_datetime,
    "VALUE" as value,
    "LDS_IS_DELETED" as lds_is_deleted,
    "PUBLISHER_ORGANISATION_CODE" as publisher_organisation_code,
    "CLINICAL_SYSTEM" as clinical_system,
    "SOURCE_EXTRACTION_DATE" as source_extraction_date,
    "LDS_TRANSFORM_DATETIME" as lds_transform_datetime,
    "OBSERVATION_ID" as observation_id,
    "PROVIDER_ORGANISATION_ID" as provider_organisation_id,
    "REFERRAL_SNOMED_CODE" as referral_snomed_code,
    "REFERRAL_SNOMED_NAME" as referral_snomed_name
from {{ source('olids', 'REFERRAL_REQUEST') }}
