{{
    config(
        description="Raw layer (OLIDS stable layer - cleaned and filtered patient records). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.OLIDS.MEDICATION_STATEMENT \ndbt: source(''olids'', ''MEDICATION_STATEMENT'') \nColumns:\n  ID -> id\n  LDS_SOURCE_RECORD_ID -> lds_source_record_id\n  PATIENT_ID -> patient_id\n  PERSON_ID -> person_id\n  PUBLISHER_ORGANISATION_ID -> publisher_organisation_id\n  PROVIDER_ORGANISATION_ID -> provider_organisation_id\n  AUTHOR_ORGANISATION_ID -> author_organisation_id\n  PRACTITIONER_ID -> practitioner_id\n  ENCOUNTER_ID -> encounter_id\n  OBSERVATION_ID -> observation_id\n  ALLERGY_INTOLERANCE_ID -> allergy_intolerance_id\n  DIAGNOSTIC_ORDER_ID -> diagnostic_order_id\n  REFERRAL_REQUEST_ID -> referral_request_id\n  CLINICAL_EFFECTIVE_DATE -> clinical_effective_date\n  CLINICAL_EFFECTIVE_DATE_PRECISION_SOURCE_CONCEPT_ID -> clinical_effective_date_precision_source_concept_id\n  DATE_PRECISION_SOURCE_CODE -> date_precision_source_code\n  DATE_PRECISION_SOURCE_DISPLAY -> date_precision_source_display\n  DATE_PRECISION_CODE -> date_precision_code\n  DATE_PRECISION_DISPLAY -> date_precision_display\n  CANCELLATION_DATE -> cancellation_date\n  DOSE -> dose\n  QUANTITY_VALUE_DESCRIPTION -> quantity_value_description\n  QUANTITY_VALUE -> quantity_value\n  QUANTITY_UNIT -> quantity_unit\n  AUTHORISATION_TYPE_SOURCE_CONCEPT_ID -> authorisation_type_source_concept_id\n  AUTHORISATION_TYPE_SOURCE_CODE -> authorisation_type_source_code\n  AUTHORISATION_TYPE_SOURCE_DISPLAY -> authorisation_type_source_display\n  AUTHORISATION_TYPE_CODE -> authorisation_type_code\n  AUTHORISATION_TYPE_DISPLAY -> authorisation_type_display\n  MEDICATION_NAME -> medication_name\n  MEDICATION_STATEMENT_SOURCE_CONCEPT_ID -> medication_statement_source_concept_id\n  SOURCE_CODE -> source_code\n  SOURCE_DISPLAY -> source_display\n  SOURCE_SYSTEM -> source_system\n  MAPPED_CONCEPT_ID -> mapped_concept_id\n  MAPPED_CONCEPT_CODE -> mapped_concept_code\n  MAPPED_CONCEPT_DISPLAY -> mapped_concept_display\n  TARGET_SYSTEM -> target_system\n  BNF_CHAPTER -> bnf_chapter\n  BNF_SECTION -> bnf_section\n  BNF_CODE -> bnf_code\n  BNF_NAME -> bnf_name\n  BNF_REFERENCE -> bnf_reference\n  AGE_AT_EVENT -> age_at_event\n  AGE_AT_EVENT_BABY -> age_at_event_baby\n  AGE_AT_EVENT_NEONATE -> age_at_event_neonate\n  ISSUE_METHOD -> issue_method\n  DATE_RECORDED -> date_recorded\n  IS_ACTIVE -> is_active\n  IS_CONFIDENTIAL -> is_confidential\n  EXPIRY_DATE -> expiry_date\n  LDS_IS_DELETED -> lds_is_deleted\n  PUBLISHER_ORGANISATION_CODE -> publisher_organisation_code\n  CLINICAL_SYSTEM -> clinical_system\n  SOURCE_EXTRACTION_DATE -> source_extraction_date\n  LDS_TRANSFORM_DATETIME -> lds_transform_datetime"
    )
}}
select
    "ID" as id,
    "LDS_SOURCE_RECORD_ID" as lds_source_record_id,
    "PATIENT_ID" as patient_id,
    "PERSON_ID" as person_id,
    "PUBLISHER_ORGANISATION_ID" as publisher_organisation_id,
    "PROVIDER_ORGANISATION_ID" as provider_organisation_id,
    "AUTHOR_ORGANISATION_ID" as author_organisation_id,
    "PRACTITIONER_ID" as practitioner_id,
    "ENCOUNTER_ID" as encounter_id,
    "OBSERVATION_ID" as observation_id,
    "ALLERGY_INTOLERANCE_ID" as allergy_intolerance_id,
    "DIAGNOSTIC_ORDER_ID" as diagnostic_order_id,
    "REFERRAL_REQUEST_ID" as referral_request_id,
    "CLINICAL_EFFECTIVE_DATE" as clinical_effective_date,
    "CLINICAL_EFFECTIVE_DATE_PRECISION_SOURCE_CONCEPT_ID" as clinical_effective_date_precision_source_concept_id,
    "DATE_PRECISION_SOURCE_CODE" as date_precision_source_code,
    "DATE_PRECISION_SOURCE_DISPLAY" as date_precision_source_display,
    "DATE_PRECISION_CODE" as date_precision_code,
    "DATE_PRECISION_DISPLAY" as date_precision_display,
    "CANCELLATION_DATE" as cancellation_date,
    "DOSE" as dose,
    "QUANTITY_VALUE_DESCRIPTION" as quantity_value_description,
    "QUANTITY_VALUE" as quantity_value,
    "QUANTITY_UNIT" as quantity_unit,
    "AUTHORISATION_TYPE_SOURCE_CONCEPT_ID" as authorisation_type_source_concept_id,
    "AUTHORISATION_TYPE_SOURCE_CODE" as authorisation_type_source_code,
    "AUTHORISATION_TYPE_SOURCE_DISPLAY" as authorisation_type_source_display,
    "AUTHORISATION_TYPE_CODE" as authorisation_type_code,
    "AUTHORISATION_TYPE_DISPLAY" as authorisation_type_display,
    "MEDICATION_NAME" as medication_name,
    "MEDICATION_STATEMENT_SOURCE_CONCEPT_ID" as medication_statement_source_concept_id,
    "SOURCE_CODE" as source_code,
    "SOURCE_DISPLAY" as source_display,
    "SOURCE_SYSTEM" as source_system,
    "MAPPED_CONCEPT_ID" as mapped_concept_id,
    "MAPPED_CONCEPT_CODE" as mapped_concept_code,
    "MAPPED_CONCEPT_DISPLAY" as mapped_concept_display,
    "TARGET_SYSTEM" as target_system,
    "BNF_CHAPTER" as bnf_chapter,
    "BNF_SECTION" as bnf_section,
    "BNF_CODE" as bnf_code,
    "BNF_NAME" as bnf_name,
    "BNF_REFERENCE" as bnf_reference,
    "AGE_AT_EVENT" as age_at_event,
    "AGE_AT_EVENT_BABY" as age_at_event_baby,
    "AGE_AT_EVENT_NEONATE" as age_at_event_neonate,
    "ISSUE_METHOD" as issue_method,
    "DATE_RECORDED" as date_recorded,
    "IS_ACTIVE" as is_active,
    "IS_CONFIDENTIAL" as is_confidential,
    "EXPIRY_DATE" as expiry_date,
    "LDS_IS_DELETED" as lds_is_deleted,
    "PUBLISHER_ORGANISATION_CODE" as publisher_organisation_code,
    "CLINICAL_SYSTEM" as clinical_system,
    "SOURCE_EXTRACTION_DATE" as source_extraction_date,
    "LDS_TRANSFORM_DATETIME" as lds_transform_datetime
from {{ source('olids', 'MEDICATION_STATEMENT') }}
