{{
    config(
        description="Raw layer (OLIDS stable layer - cleaned and filtered patient records). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.OLIDS.APPOINTMENT \ndbt: source(''olids'', ''APPOINTMENT'') \nColumns:\n  ID -> id\n  LDS_SOURCE_RECORD_ID -> lds_source_record_id\n  PATIENT_ID -> patient_id\n  PERSON_ID -> person_id\n  PUBLISHER_ORGANISATION_ID -> publisher_organisation_id\n  PROVIDER_ORGANISATION_ID -> provider_organisation_id\n  AUTHOR_ORGANISATION_ID -> author_organisation_id\n  SLOT_ID -> slot_id\n  PRACTITIONER_IN_ROLE_ID -> practitioner_in_role_id\n  SCHEDULE_ID -> schedule_id\n  START_DATE -> start_date\n  PLANNED_DURATION_MINS -> planned_duration_mins\n  ACTUAL_DURATION_MINS -> actual_duration_mins\n  APPOINTMENT_STATUS_SOURCE_CONCEPT_ID -> appointment_status_source_concept_id\n  APPOINTMENT_STATUS_DERIVED -> appointment_status_derived\n  APPOINTMENT_STATUS_SOURCE_CODE -> appointment_status_source_code\n  APPOINTMENT_STATUS_SOURCE_DISPLAY -> appointment_status_source_display\n  APPOINTMENT_STATUS_CODE -> appointment_status_code\n  APPOINTMENT_STATUS_DISPLAY -> appointment_status_display\n  PATIENT_WAIT_MINS -> patient_wait_mins\n  PATIENT_DELAY_MINS -> patient_delay_mins\n  DATETIME_BOOKED -> datetime_booked\n  DATETIME_SENT_IN -> datetime_sent_in\n  DATETIME_LEFT -> datetime_left\n  CANCELLED_DATE -> cancelled_date\n  APPOINTMENT_TYPE -> appointment_type\n  AGE_AT_EVENT -> age_at_event\n  AGE_AT_EVENT_BABY -> age_at_event_baby\n  AGE_AT_EVENT_NEONATE -> age_at_event_neonate\n  BOOKING_METHOD_SOURCE_CONCEPT_ID -> booking_method_source_concept_id\n  BOOKING_METHOD_SOURCE_CODE -> booking_method_source_code\n  BOOKING_METHOD_SOURCE_DISPLAY -> booking_method_source_display\n  BOOKING_METHOD_CODE -> booking_method_code\n  BOOKING_METHOD_DISPLAY -> booking_method_display\n  CONTACT_MODE_SOURCE_CONCEPT_ID -> contact_mode_source_concept_id\n  CONTACT_MODE_SOURCE_CODE -> contact_mode_source_code\n  CONTACT_MODE_SOURCE_DISPLAY -> contact_mode_source_display\n  CONTACT_MODE_CODE -> contact_mode_code\n  CONTACT_MODE_DISPLAY -> contact_mode_display\n  IS_BLOCKED -> is_blocked\n  NATIONAL_SLOT_CATEGORY_NAME -> national_slot_category_name\n  CONTEXT_TYPE -> context_type\n  SERVICE_SETTING -> service_setting\n  NATIONAL_SLOT_CATEGORY_DESCRIPTION -> national_slot_category_description\n  CSDS_CARE_CONTACT_IDENTIFIER -> csds_care_contact_identifier\n  LDS_IS_DELETED -> lds_is_deleted\n  PUBLISHER_ORGANISATION_CODE -> publisher_organisation_code\n  CLINICAL_SYSTEM -> clinical_system\n  SOURCE_EXTRACTION_DATE -> source_extraction_date\n  LDS_TRANSFORM_DATETIME -> lds_transform_datetime"
    )
}}
select
    "ID" as id,
    "LDS_SOURCE_RECORD_ID" as lds_source_record_id,
    "PATIENT_ID" as patient_id,
    "PERSON_ID" as person_id,
    "PUBLISHER_ORGANISATION_ID" as publisher_organisation_id,
    "PROVIDER_ORGANISATION_ID" as provider_organisation_id,
    "AUTHOR_ORGANISATION_ID" as author_organisation_id,
    "SLOT_ID" as slot_id,
    "PRACTITIONER_IN_ROLE_ID" as practitioner_in_role_id,
    "SCHEDULE_ID" as schedule_id,
    "START_DATE" as start_date,
    "PLANNED_DURATION_MINS" as planned_duration_mins,
    "ACTUAL_DURATION_MINS" as actual_duration_mins,
    "APPOINTMENT_STATUS_SOURCE_CONCEPT_ID" as appointment_status_source_concept_id,
    "APPOINTMENT_STATUS_DERIVED" as appointment_status_derived,
    "APPOINTMENT_STATUS_SOURCE_CODE" as appointment_status_source_code,
    "APPOINTMENT_STATUS_SOURCE_DISPLAY" as appointment_status_source_display,
    "APPOINTMENT_STATUS_CODE" as appointment_status_code,
    "APPOINTMENT_STATUS_DISPLAY" as appointment_status_display,
    "PATIENT_WAIT_MINS" as patient_wait_mins,
    "PATIENT_DELAY_MINS" as patient_delay_mins,
    "DATETIME_BOOKED" as datetime_booked,
    "DATETIME_SENT_IN" as datetime_sent_in,
    "DATETIME_LEFT" as datetime_left,
    "CANCELLED_DATE" as cancelled_date,
    "APPOINTMENT_TYPE" as appointment_type,
    "AGE_AT_EVENT" as age_at_event,
    "AGE_AT_EVENT_BABY" as age_at_event_baby,
    "AGE_AT_EVENT_NEONATE" as age_at_event_neonate,
    "BOOKING_METHOD_SOURCE_CONCEPT_ID" as booking_method_source_concept_id,
    "BOOKING_METHOD_SOURCE_CODE" as booking_method_source_code,
    "BOOKING_METHOD_SOURCE_DISPLAY" as booking_method_source_display,
    "BOOKING_METHOD_CODE" as booking_method_code,
    "BOOKING_METHOD_DISPLAY" as booking_method_display,
    "CONTACT_MODE_SOURCE_CONCEPT_ID" as contact_mode_source_concept_id,
    "CONTACT_MODE_SOURCE_CODE" as contact_mode_source_code,
    "CONTACT_MODE_SOURCE_DISPLAY" as contact_mode_source_display,
    "CONTACT_MODE_CODE" as contact_mode_code,
    "CONTACT_MODE_DISPLAY" as contact_mode_display,
    "IS_BLOCKED" as is_blocked,
    "NATIONAL_SLOT_CATEGORY_NAME" as national_slot_category_name,
    "CONTEXT_TYPE" as context_type,
    "SERVICE_SETTING" as service_setting,
    "NATIONAL_SLOT_CATEGORY_DESCRIPTION" as national_slot_category_description,
    "CSDS_CARE_CONTACT_IDENTIFIER" as csds_care_contact_identifier,
    "LDS_IS_DELETED" as lds_is_deleted,
    "PUBLISHER_ORGANISATION_CODE" as publisher_organisation_code,
    "CLINICAL_SYSTEM" as clinical_system,
    "SOURCE_EXTRACTION_DATE" as source_extraction_date,
    "LDS_TRANSFORM_DATETIME" as lds_transform_datetime
from {{ source('olids', 'APPOINTMENT') }}
