{{
    config(
        materialized = 'table',
        tags = ['asc_cld']
    )
}}

select
    la_code,
    {{ consistent_sk_patient_id_format('pseudo_nhs_number')}}  as sk_patient_id,
    reporting_period_start_date,
    reporting_period_end_date,
    la_person_unique_identifier,
    gender,
    ethnicity,
    client_type,
    primary_support_reason,
    accommodation_status,
    employment_status,
    has_unpaid_carer,
    autism_spectrum_disorder_asd,
    visual_impairment,
    hearing_impairment,
    dementia,
    client_funding_status,
    event_type,
    event_reference,
    event_start_date,
    event_end_date,
    event_description,
    event_outcome,
    request_route_of_access,
    assessment_type,
    eligible_needs_identified,
    informal_carer_involved_in_assessment,
    method_of_assessment,
    total_hrs_caring_per_week,
    no_of_adults_being_cared_for,
    adult_1_linked_person_id,
    adult_2_linked_person_id,
    adult_3_linked_person_id,
    service_type,
    service_component,
    delivery_mechanism,
    provider_cqc_location_name,
    provider_cqc_location_id,
    review_reason,
    review_outcomes_achieved,
    method_of_review,
    unit_cost,
    cost_frequency_unit_type,
    planned_units_per_week,
    full_cost_client,
    dm_age_at_reporting_period_start_date,
    dm_ccg_of_practice_from_nhs_number,
    dm_ccg_of_residence_from_nhs_number,
    dm_practice_code_from_nhs_number,
    dm_import_log_id,
    dm_row_id,
    dm_flow_id,
    dm_submitted_file_name,
    dm_specification,
    dm_received_date
from {{ ref('raw_asc_cld_adult_social_care_cld') }}

