select
    vaccine_order,
    vaccine_id,
    vaccine_name,
    dose_number,
    diseases_protected_against,
    -- vaccine_code,
    trade_name,
    administration_route,
    schedule_age,
    maximum_age_days,
    next_dose_vaccine_id,
    eligible_age_from_days,
    eligible_age_to_days,
    administered_cluster_id,
    drug_cluster_id,
    declined_cluster_id,
    contraindicated_cluster_id,
from {{ ref('raw_reference_imms_schedule_adult_latest') }}
