-- Aggregate field coverage only; no source values are returned.
with stats as (
    select object_construct(
        'source_record_id', object_construct('populated', count(source_record_id), 'blank', count_if(trim(source_record_id::varchar) = '')),
        'person_id', object_construct('populated', count(person_id), 'blank', count_if(trim(person_id::varchar) = '')),
        'sk_patient_id', object_construct('populated', count(sk_patient_id), 'blank', count_if(trim(sk_patient_id::varchar) = '')),
        'patient_id', object_construct('populated', count(patient_id), 'blank', count_if(trim(patient_id::varchar) = '')),
        'encounter_id', object_construct('populated', count(encounter_id), 'blank', count_if(trim(encounter_id::varchar) = '')),
        'practitioner_id', object_construct('populated', count(practitioner_id), 'blank', count_if(trim(practitioner_id::varchar) = '')),
        'unique_booking_reference_number', object_construct('populated', count(unique_booking_reference_number), 'blank', count_if(trim(unique_booking_reference_number::varchar) = '')),
        'clinical_effective_date', object_construct('populated', count(clinical_effective_date), 'blank', count_if(trim(clinical_effective_date::varchar) = '')),
        'date_recorded', object_construct('populated', count(date_recorded), 'blank', count_if(trim(date_recorded::varchar) = '')),
        'mode', object_construct('populated', count(mode), 'blank', count_if(trim(mode::varchar) = '')),
        'is_outgoing_referral', object_construct('populated', count(is_outgoing_referral), 'blank', count_if(trim(is_outgoing_referral::varchar) = '')),
        'is_review', object_construct('populated', count(is_review), 'blank', count_if(trim(is_review::varchar) = '')),
        'referring_organisation_id', object_construct('populated', count(referring_organisation_id), 'blank', count_if(trim(referring_organisation_id::varchar) = '')),
        'referring_organisation_code', object_construct('populated', count(referring_organisation_code), 'blank', count_if(trim(referring_organisation_code::varchar) = '')),
        'referring_organisation_code_authority', object_construct('populated', count(referring_organisation_code_authority), 'blank', count_if(trim(referring_organisation_code_authority::varchar) = '')),
        'referring_organisation_name', object_construct('populated', count(referring_organisation_name), 'blank', count_if(trim(referring_organisation_name::varchar) = '')),
        'receiving_organisation_id', object_construct('populated', count(receiving_organisation_id), 'blank', count_if(trim(receiving_organisation_id::varchar) = '')),
        'receiving_organisation_code', object_construct('populated', count(receiving_organisation_code), 'blank', count_if(trim(receiving_organisation_code::varchar) = '')),
        'receiving_organisation_code_authority', object_construct('populated', count(receiving_organisation_code_authority), 'blank', count_if(trim(receiving_organisation_code_authority::varchar) = '')),
        'receiving_organisation_name', object_construct('populated', count(receiving_organisation_name), 'blank', count_if(trim(receiving_organisation_name::varchar) = '')),
        'publisher_organisation_id', object_construct('populated', count(publisher_organisation_id), 'blank', count_if(trim(publisher_organisation_id::varchar) = '')),
        'publisher_organisation_code', object_construct('populated', count(publisher_organisation_code), 'blank', count_if(trim(publisher_organisation_code::varchar) = '')),
        'publisher_organisation_code_authority', object_construct('populated', count(publisher_organisation_code_authority), 'blank', count_if(trim(publisher_organisation_code_authority::varchar) = '')),
        'publisher_organisation_name', object_construct('populated', count(publisher_organisation_name), 'blank', count_if(trim(publisher_organisation_name::varchar) = '')),
        'source_publisher_organisation_code', object_construct('populated', count(source_publisher_organisation_code), 'blank', count_if(trim(source_publisher_organisation_code::varchar) = '')),
        'referral_request_source_concept_id', object_construct('populated', count(referral_request_source_concept_id), 'blank', count_if(trim(referral_request_source_concept_id::varchar) = '')),
        'referral_code', object_construct('populated', count(referral_code), 'blank', count_if(trim(referral_code::varchar) = '')),
        'referral_name', object_construct('populated', count(referral_name), 'blank', count_if(trim(referral_name::varchar) = '')),
        'referral_coding_system', object_construct('populated', count(referral_coding_system), 'blank', count_if(trim(referral_coding_system::varchar) = '')),
        'mapped_concept_code', object_construct('populated', count(mapped_concept_code), 'blank', count_if(trim(mapped_concept_code::varchar) = '')),
        'mapped_concept_coding_system', object_construct('populated', count(mapped_concept_coding_system), 'blank', count_if(trim(mapped_concept_coding_system::varchar) = '')),
        'mapped_concept_display', object_construct('populated', count(mapped_concept_display), 'blank', count_if(trim(mapped_concept_display::varchar) = '')),
        'referral_request_priority_source_concept_id', object_construct('populated', count(referral_request_priority_source_concept_id), 'blank', count_if(trim(referral_request_priority_source_concept_id::varchar) = '')),
        'priority_code', object_construct('populated', count(priority_code), 'blank', count_if(trim(priority_code::varchar) = '')),
        'priority_name', object_construct('populated', count(priority_name), 'blank', count_if(trim(priority_name::varchar) = '')),
        'referral_request_specialty_source_concept_id', object_construct('populated', count(referral_request_specialty_source_concept_id), 'blank', count_if(trim(referral_request_specialty_source_concept_id::varchar) = '')),
        'specialty_code', object_construct('populated', count(specialty_code), 'blank', count_if(trim(specialty_code::varchar) = '')),
        'specialty_name', object_construct('populated', count(specialty_name), 'blank', count_if(trim(specialty_name::varchar) = '')),
        'referral_request_type_source_concept_id', object_construct('populated', count(referral_request_type_source_concept_id), 'blank', count_if(trim(referral_request_type_source_concept_id::varchar) = '')),
        'referral_type_code', object_construct('populated', count(referral_type_code), 'blank', count_if(trim(referral_type_code::varchar) = '')),
        'referral_type_name', object_construct('populated', count(referral_type_name), 'blank', count_if(trim(referral_type_name::varchar) = '')),
        'clinical_effective_date_precision_source_concept_id', object_construct('populated', count(clinical_effective_date_precision_source_concept_id), 'blank', count_if(trim(clinical_effective_date_precision_source_concept_id::varchar) = '')),
        'clinical_date_precision_code', object_construct('populated', count(clinical_date_precision_code), 'blank', count_if(trim(clinical_date_precision_code::varchar) = '')),
        'clinical_date_precision_name', object_construct('populated', count(clinical_date_precision_name), 'blank', count_if(trim(clinical_date_precision_name::varchar) = '')),
        'source_transform_datetime', object_construct('populated', count(source_transform_datetime), 'blank', count_if(trim(source_transform_datetime::varchar) = '')),
        'lds_source_record_id', object_construct('populated', count(lds_source_record_id), 'blank', count_if(trim(lds_source_record_id::varchar) = ''))
    ) as field_counts
    from {{ ref('fct_gp_referral_request') }}
)
select f.key as column_name, f.value as coverage
from stats, lateral flatten(input => stats.field_counts) as f
