{% macro nice_ref(model_name, reference='current') %}
{#-
    Adapt a current or monthly input generated by one calculation macro.
    Args: model_name is the current model name; reference is current or by_month.
    Returns: a current subquery or unchanged monthly relation for a FROM clause.
    Current inputs retain their last-built evidence but use today's evaluation date.
    Both paired models must have identical physical columns. Callers supply an alias.
-#}
{% if reference not in ['current', 'by_month'] %}
    {{ exceptions.raise_compiler_error('Unsupported NICE reference: ' ~ reference) }}
{% endif %}
{% if reference == 'current' %}
    (SELECT * REPLACE (CURRENT_DATE()::DATE AS reporting_date) FROM {{ ref(model_name) }})
{% else %}
    {{ ref(model_name ~ '_by_month') }}
{% endif %}
{% endmacro %}
