{% macro nice_ref(model_name, reference='current') %}
{#-
    Select a current or monthly relation generated by one calculation macro.
    Args: model_name is the current model name; reference is current or by_month.
    Returns: a dbt Relation. Both paired models must have identical physical columns.
-#}
{% if reference not in ['current', 'by_month'] %}
    {{ exceptions.raise_compiler_error('Unsupported NICE reference: ' ~ reference) }}
{% endif %}
{{ return(ref(model_name if reference == 'current' else model_name ~ '_by_month')) }}
{% endmacro %}
