-- Whole-table column coverage; no identifiers or patient records are returned.
with stats as (
    select object_construct(
        'appointment_id', object_construct('populated', count(appointment_id), 'null', count(*) - count(appointment_id), 'blank', count_if(trim(appointment_id::varchar) = ''), 'missing', count_if(nullif(trim(appointment_id::varchar), '') is null)),
        'ubrn_id', object_construct('populated', count(ubrn_id), 'null', count(*) - count(ubrn_id), 'blank', count_if(trim(ubrn_id::varchar) = ''), 'missing', count_if(nullif(trim(ubrn_id::varchar), '') is null)),
        'ubrn', object_construct('populated', count(ubrn), 'null', count(*) - count(ubrn), 'blank', count_if(trim(ubrn::varchar) = ''), 'missing', count_if(nullif(trim(ubrn::varchar), '') is null)),
        'sk_patient_id', object_construct('populated', count(sk_patient_id), 'null', count(*) - count(sk_patient_id), 'blank', count_if(trim(sk_patient_id::varchar) = ''), 'missing', count_if(nullif(trim(sk_patient_id::varchar), '') is null)),
        'appointment_at', object_construct('populated', count(appointment_at), 'null', count(*) - count(appointment_at), 'blank', count_if(trim(appointment_at::varchar) = ''), 'missing', count_if(nullif(trim(appointment_at::varchar), '') is null)),
        'service_id', object_construct('populated', count(service_id), 'null', count(*) - count(service_id), 'blank', count_if(trim(service_id::varchar) = ''), 'missing', count_if(nullif(trim(service_id::varchar), '') is null)),
        'service_name', object_construct('populated', count(service_name), 'null', count(*) - count(service_name), 'blank', count_if(trim(service_name::varchar) = ''), 'missing', count_if(nullif(trim(service_name::varchar), '') is null)),
        'service_specialty_code', object_construct('populated', count(service_specialty_code), 'null', count(*) - count(service_specialty_code), 'blank', count_if(trim(service_specialty_code::varchar) = ''), 'missing', count_if(nullif(trim(service_specialty_code::varchar), '') is null)),
        'service_specialty_name', object_construct('populated', count(service_specialty_name), 'null', count(*) - count(service_specialty_name), 'blank', count_if(trim(service_specialty_name::varchar) = ''), 'missing', count_if(nullif(trim(service_specialty_name::varchar), '') is null)),
        'provider_organisation_code', object_construct('populated', count(provider_organisation_code), 'null', count(*) - count(provider_organisation_code), 'blank', count_if(trim(provider_organisation_code::varchar) = ''), 'missing', count_if(nullif(trim(provider_organisation_code::varchar), '') is null)),
        'provider_organisation_name', object_construct('populated', count(provider_organisation_name), 'null', count(*) - count(provider_organisation_name), 'blank', count_if(trim(provider_organisation_name::varchar) = ''), 'missing', count_if(nullif(trim(provider_organisation_name::varchar), '') is null)),
        'site_code', object_construct('populated', count(site_code), 'null', count(*) - count(site_code), 'blank', count_if(trim(site_code::varchar) = ''), 'missing', count_if(nullif(trim(site_code::varchar), '') is null)),
        'site_name', object_construct('populated', count(site_name), 'null', count(*) - count(site_name), 'blank', count_if(trim(site_name::varchar) = ''), 'missing', count_if(nullif(trim(site_name::varchar), '') is null)),
        'appointment_type_code', object_construct('populated', count(appointment_type_code), 'null', count(*) - count(appointment_type_code), 'blank', count_if(trim(appointment_type_code::varchar) = ''), 'missing', count_if(nullif(trim(appointment_type_code::varchar), '') is null)),
        'appointment_type_name', object_construct('populated', count(appointment_type_name), 'null', count(*) - count(appointment_type_name), 'blank', count_if(trim(appointment_type_name::varchar) = ''), 'missing', count_if(nullif(trim(appointment_type_name::varchar), '') is null)),
        'action_count', object_construct('populated', count(action_count), 'null', count(*) - count(action_count), 'blank', count_if(trim(action_count::varchar) = ''), 'missing', count_if(nullif(trim(action_count::varchar), '') is null)),
        'recorded_booking_action_count', object_construct('populated', count(recorded_booking_action_count), 'null', count(*) - count(recorded_booking_action_count), 'blank', count_if(trim(recorded_booking_action_count::varchar) = ''), 'missing', count_if(nullif(trim(recorded_booking_action_count::varchar), '') is null)),
        'first_observed_action_at', object_construct('populated', count(first_observed_action_at), 'null', count(*) - count(first_observed_action_at), 'blank', count_if(trim(first_observed_action_at::varchar) = ''), 'missing', count_if(nullif(trim(first_observed_action_at::varchar), '') is null)),
        'last_observed_action_at', object_construct('populated', count(last_observed_action_at), 'null', count(*) - count(last_observed_action_at), 'blank', count_if(trim(last_observed_action_at::varchar) = ''), 'missing', count_if(nullif(trim(last_observed_action_at::varchar), '') is null)),
        'latest_action_id', object_construct('populated', count(latest_action_id), 'null', count(*) - count(latest_action_id), 'blank', count_if(trim(latest_action_id::varchar) = ''), 'missing', count_if(nullif(trim(latest_action_id::varchar), '') is null)),
        'latest_appointment_action_id', object_construct('populated', count(latest_appointment_action_id), 'null', count(*) - count(latest_appointment_action_id), 'blank', count_if(trim(latest_appointment_action_id::varchar) = ''), 'missing', count_if(nullif(trim(latest_appointment_action_id::varchar), '') is null)),
        'latest_appointment_action_at', object_construct('populated', count(latest_appointment_action_at), 'null', count(*) - count(latest_appointment_action_at), 'blank', count_if(trim(latest_appointment_action_at::varchar) = ''), 'missing', count_if(nullif(trim(latest_appointment_action_at::varchar), '') is null)),
        'latest_appointment_action_code', object_construct('populated', count(latest_appointment_action_code), 'null', count(*) - count(latest_appointment_action_code), 'blank', count_if(trim(latest_appointment_action_code::varchar) = ''), 'missing', count_if(nullif(trim(latest_appointment_action_code::varchar), '') is null)),
        'latest_appointment_action_name', object_construct('populated', count(latest_appointment_action_name), 'null', count(*) - count(latest_appointment_action_name), 'blank', count_if(trim(latest_appointment_action_name::varchar) = ''), 'missing', count_if(nullif(trim(latest_appointment_action_name::varchar), '') is null)),
        'latest_appointment_action_reason_code', object_construct('populated', count(latest_appointment_action_reason_code), 'null', count(*) - count(latest_appointment_action_reason_code), 'blank', count_if(trim(latest_appointment_action_reason_code::varchar) = ''), 'missing', count_if(nullif(trim(latest_appointment_action_reason_code::varchar), '') is null)),
        'latest_appointment_action_reason_name', object_construct('populated', count(latest_appointment_action_reason_name), 'null', count(*) - count(latest_appointment_action_reason_name), 'blank', count_if(trim(latest_appointment_action_reason_name::varchar) = ''), 'missing', count_if(nullif(trim(latest_appointment_action_reason_name::varchar), '') is null))
    ) as fields
    from {{ ref('fct_ers_appointment') }}
)
select f.key as column_name, f.value as coverage
from stats, lateral flatten(input => fields) f
