--person level vaccination record for adults
{{
    config(
        materialized='table',
        tags=['adult_imms'])
}}
--Multiple lines per preson
SELECT 
ec.PERSON_ID
,ec.BIRTH_DATE_APPROX
,ec.AGE
,ec.GENDER
,ec.AGE_BAND_5Y
,ec.IS_CARE_HOME_RESIDENT
,ec.IS_IMMUNOSUPPRESSED
,ec.IN_PPV_CLINICAL_RISK_GROUP
,ec.IN_RSV_CLINICAL_RISK_GROUP
,ec.IS_PREGNANT
,ec.TURN_65_AFTER_SEP_2023
,ec.VACCINE_ORDER
,ec.VACCINE_ID
,ec.VACCINE_NAME
,ec.DOSE_NUMBER
,ec.ELIGIBLE_FROM_DATE 
,ec.ELIGIBLE_TO_DATE
,ec.MAXIMUM_AGE_DAYS
--Add in additional logic for where vaccination events are missing.
,CASE 
---PPV-------------------------------------------------------------------WHEN VACCINATIONS ARE MISSING
--PPV_1 routine for people aged 65+
WHEN ve.EVENT_DATE IS NULL AND ec.IN_PPV_CLINICAL_RISK_GROUP = FALSE AND ec.VACCINE_ID = 'PPV_1' AND ec.ELIGIBLE_FROM_DATE < CURRENT_DATE AND ec.currently_eligible THEN 'Overdue'
WHEN ve.EVENT_DATE IS NULL AND ec.IN_PPV_CLINICAL_RISK_GROUP = FALSE AND ec.VACCINE_ID = 'PPV_1' AND ec.currently_eligible = FALSE AND ec.AGE_DAYS_APPROX <= ec.maximum_age_days THEN 'Not due yet'
WHEN ve.EVENT_DATE IS NULL AND ec.IN_PPV_CLINICAL_RISK_GROUP = FALSE AND ec.VACCINE_ID in ('PPV_1B') THEN 'Not applicable'
--PPV_1B routine for immunosuppressed and other conditions 
WHEN ve.EVENT_DATE IS NULL AND ec.IN_PPV_CLINICAL_RISK_GROUP AND ec.VACCINE_ID = 'PPV_1B' AND ec.ELIGIBLE_FROM_DATE < CURRENT_DATE AND ec.currently_eligible THEN 'Overdue'
WHEN ve.EVENT_DATE IS NULL AND ec.IN_PPV_CLINICAL_RISK_GROUP AND ec.VACCINE_ID = 'PPV_1B' AND ec.currently_eligible = FALSE AND ec.AGE_DAYS_APPROX <= ec.maximum_age_days THEN 'Not due yet'
WHEN ve.EVENT_DATE IS NULL AND ec.IN_PPV_CLINICAL_RISK_GROUP AND ec.VACCINE_ID in ('PPV_1') THEN 'Not applicable'
--SHINGLES---------------------------------------------------------------WHEN VACCINATIONS ARE MISSING
--SHING_1 turned 65 after 1st sep 2023
WHEN ve.EVENT_DATE IS NULL AND ec.TURN_65_AFTER_SEP_2023 AND ec.IS_IMMUNOSUPPRESSED = FALSE AND ec.VACCINE_ID in ('SHING_1','SHING_2') AND ec.ELIGIBLE_FROM_DATE <= CURRENT_DATE AND ec.currently_eligible THEN 'Overdue'
WHEN ve.EVENT_DATE IS NULL AND ec.TURN_65_AFTER_SEP_2023 AND ec.IS_IMMUNOSUPPRESSED = FALSE AND ec.VACCINE_ID in ('SHING_1','SHING_2') AND ec.currently_eligible = FALSE AND ec.AGE_DAYS_APPROX <= ec.maximum_age_days THEN 'Not due yet'
WHEN ve.EVENT_DATE IS NULL AND ec.TURN_65_AFTER_SEP_2023 AND ec.IS_IMMUNOSUPPRESSED = FALSE AND ec.VACCINE_ID in ('SHING_1B','SHING_2B','SHING_1C','SHING_2C') THEN 'Not applicable'
--SHING 1B TURNED 65 BEFORE 1st Sep 2023 - ROUTINE CATCH UP 70-79
WHEN ve.EVENT_DATE IS NULL AND ec.TURN_65_AFTER_SEP_2023 = FALSE AND ec.IS_IMMUNOSUPPRESSED = FALSE AND ec.VACCINE_ID in ('SHING_1B','SHING_2B') AND ec.ELIGIBLE_FROM_DATE <= CURRENT_DATE AND ec.currently_eligible THEN 'Overdue'
WHEN ve.EVENT_DATE IS NULL AND ec.TURN_65_AFTER_SEP_2023 = FALSE AND ec.IS_IMMUNOSUPPRESSED = FALSE AND ec.VACCINE_ID in ('SHING_1B','SHING_2B') AND ec.currently_eligible = FALSE AND ec.AGE_DAYS_APPROX <= ec.maximum_age_days THEN 'Not due yet'
WHEN ve.EVENT_DATE IS NULL AND ec.TURN_65_AFTER_SEP_2023 = FALSE AND ec.IS_IMMUNOSUPPRESSED = FALSE AND ec.VACCINE_ID in ('SHING_1','SHING_2','SHING_1C','SHING_2C') THEN 'Not applicable'
--Shingles for 18+ immunosuppressed SHING_1C and SHING_2C
WHEN ve.EVENT_DATE IS NULL AND ec.IS_IMMUNOSUPPRESSED AND ec.TURN_65_AFTER_SEP_2023 = FALSE AND ec.AGE >= 18 AND ec.VACCINE_ID in ('SHING_1C','SHING_2C') AND ec.ELIGIBLE_FROM_DATE <= CURRENT_DATE AND ec.currently_eligible THEN 'Overdue'
WHEN ve.EVENT_DATE IS NULL AND ec.IS_IMMUNOSUPPRESSED AND ec.TURN_65_AFTER_SEP_2023 = FALSE AND ec.AGE >= 18 AND ec.VACCINE_ID in ('SHING_1C','SHING_2C') AND ec.currently_eligible = FALSE AND ec.AGE_DAYS_APPROX <= ec.maximum_age_days THEN 'Not due yet'
WHEN ve.EVENT_DATE IS NULL AND ec.IS_IMMUNOSUPPRESSED AND ec.TURN_65_AFTER_SEP_2023 = FALSE AND ec.AGE >= 18 AND ec.VACCINE_ID in ('SHING_1','SHING_2','SHING_1B','SHING_2B') THEN 'Not applicable'
--Shingles for 18+ immunosuppressed SHING_1C and SHING_2C AND turned 65 after 1st sep 2023
WHEN ve.EVENT_DATE IS NULL AND ec.TURN_65_AFTER_SEP_2023 AND ec.IS_IMMUNOSUPPRESSED AND ec.VACCINE_ID in ('SHING_1','SHING_2','SHING_1C','SHING_2C') AND ec.ELIGIBLE_FROM_DATE <= CURRENT_DATE AND ec.currently_eligible THEN 'Overdue'
WHEN ve.EVENT_DATE IS NULL AND ec.IS_IMMUNOSUPPRESSED AND ec.TURN_65_AFTER_SEP_2023 AND ec.AGE >= 18 AND ec.VACCINE_ID in ('SHING_1B','SHING_2B') THEN 'Not applicable'
--RSV------------------------------------------------------------WHEN VACCINATIONS ARE MISSING
--RSV_1C CURRENTLY PREGNANT 
WHEN ve.EVENT_DATE IS NULL AND ec.IS_PREGNANT AND ec.currently_eligible AND ec.VACCINE_ID in ('RSV_1C')  THEN 'Overdue'
WHEN ve.EVENT_DATE IS NULL AND ec.IS_PREGNANT AND ec.IN_RSV_CLINICAL_RISK_GROUP = FALSE AND ec.IS_CARE_HOME_RESIDENT = FALSE AND ec.currently_eligible = FALSE AND ec.VACCINE_ID in ('RSV_1', 'RSV_1B') THEN 'Not applicable'
--RSV_1 THOSE AGED 75 or OLDER starting 1st April 2026
WHEN ve.EVENT_DATE IS NULL AND ec.IS_PREGNANT = FALSE AND ec.IS_CARE_HOME_RESIDENT = FALSE AND ec.IN_RSV_CLINICAL_RISK_GROUP = FALSE AND ec.VACCINE_ID in ('RSV_1') AND  ec.ELIGIBLE_FROM_DATE <= CURRENT_DATE AND ec.currently_eligible THEN 'Overdue'
WHEN ve.EVENT_DATE IS NULL AND ec.IS_PREGNANT = FALSE AND ec.IS_CARE_HOME_RESIDENT = FALSE AND ec.IN_RSV_CLINICAL_RISK_GROUP = FALSE AND ec.VACCINE_ID in ('RSV_1') AND ec.currently_eligible = FALSE AND ec.AGE_DAYS_APPROX <= ec.maximum_age_days THEN 'Not due yet'
WHEN ve.EVENT_DATE IS NULL AND ec.IS_PREGNANT = FALSE AND ec.IS_CARE_HOME_RESIDENT = FALSE AND ec.IN_RSV_CLINICAL_RISK_GROUP = FALSE AND ec.VACCINE_ID in ('RSV_1B','RSV_1C','RSV_1D') THEN 'Not applicable'
--RSV_1B THOSE IN A CARE HOME FOR OLDER PEOPLE 
WHEN ve.EVENT_DATE IS NULL AND ec.IS_PREGNANT = FALSE AND ec.IS_CARE_HOME_RESIDENT AND ec.IN_RSV_CLINICAL_RISK_GROUP = FALSE AND ec.VACCINE_ID in ('RSV_1B') AND ec.ELIGIBLE_FROM_DATE < CURRENT_DATE AND ec.currently_eligible THEN 'Overdue'
WHEN ve.EVENT_DATE IS NULL AND ec.IS_PREGNANT = FALSE AND ec.IS_CARE_HOME_RESIDENT AND ec.IN_RSV_CLINICAL_RISK_GROUP = FALSE AND ec.VACCINE_ID in ('RSV_1B') AND ec.currently_eligible = FALSE AND ec.AGE_DAYS_APPROX <= ec.maximum_age_days THEN 'Not due yet'
WHEN ve.EVENT_DATE IS NULL AND ec.IS_PREGNANT = FALSE AND ec.IS_CARE_HOME_RESIDENT AND ec.IN_RSV_CLINICAL_RISK_GROUP = FALSE AND ec.VACCINE_ID in ('RSV_1','RSV_1C','RSV_1D') THEN 'Not applicable'
--RSV_1D IN AN RSV CLINICAL RISK GROUP new September 2026 
WHEN ve.EVENT_DATE IS NULL AND ec.IN_RSV_CLINICAL_RISK_GROUP AND ec.VACCINE_ID in ('RSV_1D') AND ec.ELIGIBLE_FROM_DATE < CURRENT_DATE AND ec.currently_eligible THEN 'Overdue'
WHEN ve.EVENT_DATE IS NULL AND ec.IN_RSV_CLINICAL_RISK_GROUP AND ec.VACCINE_ID in ('RSV_1D') AND ec.currently_eligible = FALSE AND ec.AGE_DAYS_APPROX <= ec.maximum_age_days THEN 'Not due yet'
WHEN ve.EVENT_DATE IS NULL AND ec.IN_RSV_CLINICAL_RISK_GROUP AND ec.VACCINE_ID in ('RSV_1','RSV_1B','RSV_1C') THEN 'Not applicable'
-----------All vaccinations------------------------
WHEN ve.EVENT_DATE IS NULL AND ec.AGE_DAYS_APPROX > ec.maximum_age_days THEN 'No longer eligible'
ELSE ve.vaccination_status END AS VACCINATION_STATUS
,ve.EVENT_DATE as VACCINATION_DATE
,ve.OUT_OF_SCHEDULE
,ve.AGE_AT_EVENT
FROM {{ ref('int_adult_imms_currently_eligible') }} ec
--FROM MODELLING.OLIDS_PROGRAMME.INT_ADULT_IMMS_CURRENTLY_ELIGIBLE ec
LEFT JOIN {{ ref('int_adult_imms_vaccination_events_current') }} ve ON ec.PERSON_ID = ve.PERSON_ID AND ec.VACCINE_ID = ve.VACCINE_ID  
--LEFT JOIN MODELLING.OLIDS_PROGRAMME.INT_ADULT_IMMS_VACCINATION_EVENTS_CURRENT ve ON ec.PERSON_ID = ve.PERSON_ID AND ec.VACCINE_ID = ve.VACCINE_ID   

