{{
    config(
        description="Raw layer (EMIS extract for c-ltcs pipeline from PID environment via MESH and other local lookups). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE__NCL.CLTCS.EMIS \ndbt: source(''cltcs_emis_extract'', ''EMIS'') \nColumns:\n  SK_PATIENT_ID -> sk_patient_id\n  LTC_LCS -> ltc_lcs\n  BOROUGH -> borough\n  PATIENT_DETAILS_USUAL_GP_S_ORGANISATION_CODE -> patient_details_usual_gp_s_organisation_code\n  PATIENT_DETAILS_AGE -> patient_details_age\n  PATIENT_DETAILS_DATE_OF_BIRTH -> patient_details_date_of_birth\n  PATIENT_DETAILS_GENDER -> patient_details_gender\n  PATIENT_DETAILS_ETHNIC_ORIGIN -> patient_details_ethnic_origin\n  PATIENT_DETAILS_TOWNSEND_SCORE -> patient_details_townsend_score\n  PATIENT_DETAILS_LOWER_LAYER_AREA_2001 -> patient_details_lower_layer_area_2001\n  PATIENT_DETAILS_MIDDLE_LAYER_AREA_2001 -> patient_details_middle_layer_area_2001\n  PATIENT_DETAILS_LOWER_LAYER_AREA_2011 -> patient_details_lower_layer_area_2011\n  PATIENT_DETAILS_MIDDLE_LAYER_AREA_2011 -> patient_details_middle_layer_area_2011\n  RECORD_OF_INTERPRETER_INFORMATION_EXISTS -> record_of_interpreter_information_exists\n  HOMELESSNESS_EXISTS -> homelessness_exists\n  HOUSEBOUND_EXISTS -> housebound_exists\n  CARE_HOME_RESIDENT_EXISTS -> care_home_resident_exists\n  CARDIOVASCULAR_DISEASE_EXISTS -> cardiovascular_disease_exists\n  ATRIAL_FIBRILLATION_EXISTS -> atrial_fibrillation_exists\n  HYPERTENSION_EXISTS -> hypertension_exists\n  HYPERLIPIDAEMIA_EXISTS -> hyperlipidaemia_exists\n  DIABETES_EXISTS -> diabetes_exists\n  CHRONIC_KIDNEY_DISEASE_EXISTS -> chronic_kidney_disease_exists\n  NA_FATTY_LIVER_DISEASE_EXISTS -> na_fatty_liver_disease_exists\n  COPD_EXISTS -> copd_exists\n  ASTHMA_EXISTS -> asthma_exists\n  SERIOUS_MI_EXISTS -> serious_mi_exists\n  LEARNING_DISABILITY_EXISTS -> learning_disability_exists\n  FRAILTY_EXISTS -> frailty_exists\n  SMOKING_STATUS_DATE -> smoking_status_date\n  SMOKING_STATUS_CODE_TERM -> smoking_status_code_term\n  SMOKING_STATUS_VALUE -> smoking_status_value\n  BMI_DATE -> bmi_date\n  BMI_CODE_TERM -> bmi_code_term\n  BMI_VALUE -> bmi_value\n  O_E_BP_READING_DATE -> o_e_bp_reading_date\n  O_E_BP_READING_CODE_TERM -> o_e_bp_reading_code_term\n  O_E_BP_READING_VALUE -> o_e_bp_reading_value\n  O_E_BP_READING_SECONDARY_VALUE -> o_e_bp_reading_secondary_value\n  HBA1C_DATE -> hba1_c_date\n  HBA1C_CODE_TERM -> hba1_c_code_term\n  HBA1C_VALUE -> hba1_c_value\n  EGFR_DATE -> egfr_date\n  EGFR_CODE_TERM -> egfr_code_term\n  EGFR_VALUE -> egfr_value\n  UACR_DATE -> uacr_date\n  UACR_CODE_TERM -> uacr_code_term\n  UACR_VALUE -> uacr_value\n  TC_DATE -> tc_date\n  TC_CODE_TERM -> tc_code_term\n  TC_VALUE -> tc_value\n  LDL_DATE -> ldl_date\n  LDL_CODE_TERM -> ldl_code_term\n  LDL_VALUE -> ldl_value\n  MOC_CHECK_TEST_APPOINTMENT_ON_DATE -> moc_check_test_appointment_on_date\n  MOC_FOLLOW_UP_APPOINTMENT_ON_DATE -> moc_follow_up_appointment_on_date\n  RPT_COUNT_COUNT -> rpt_count_count\n  RECORD_SOURCE -> record_source\n  GP_PRACTICE_WARNING_FLAG -> gp_practice_warning_flag\n  METADATA_FILE_PATH -> metadata_file_path\n  METADATA_FILE_ROW_NUMBER -> metadata_file_row_number\n  METADATA_RECORD_INGESTION_TIMESTAMP -> metadata_record_ingestion_timestamp\n  METADATA_FILE_CONTENT_KEY -> metadata_file_content_key\n  METADATA_FILE_LAST_MODIFIED -> metadata_file_last_modified"
    )
}}
select
    "SK_PATIENT_ID" as sk_patient_id,
    "LTC_LCS" as ltc_lcs,
    "BOROUGH" as borough,
    "PATIENT_DETAILS_USUAL_GP_S_ORGANISATION_CODE" as patient_details_usual_gp_s_organisation_code,
    "PATIENT_DETAILS_AGE" as patient_details_age,
    "PATIENT_DETAILS_DATE_OF_BIRTH" as patient_details_date_of_birth,
    "PATIENT_DETAILS_GENDER" as patient_details_gender,
    "PATIENT_DETAILS_ETHNIC_ORIGIN" as patient_details_ethnic_origin,
    "PATIENT_DETAILS_TOWNSEND_SCORE" as patient_details_townsend_score,
    "PATIENT_DETAILS_LOWER_LAYER_AREA_2001" as patient_details_lower_layer_area_2001,
    "PATIENT_DETAILS_MIDDLE_LAYER_AREA_2001" as patient_details_middle_layer_area_2001,
    "PATIENT_DETAILS_LOWER_LAYER_AREA_2011" as patient_details_lower_layer_area_2011,
    "PATIENT_DETAILS_MIDDLE_LAYER_AREA_2011" as patient_details_middle_layer_area_2011,
    "RECORD_OF_INTERPRETER_INFORMATION_EXISTS" as record_of_interpreter_information_exists,
    "HOMELESSNESS_EXISTS" as homelessness_exists,
    "HOUSEBOUND_EXISTS" as housebound_exists,
    "CARE_HOME_RESIDENT_EXISTS" as care_home_resident_exists,
    "CARDIOVASCULAR_DISEASE_EXISTS" as cardiovascular_disease_exists,
    "ATRIAL_FIBRILLATION_EXISTS" as atrial_fibrillation_exists,
    "HYPERTENSION_EXISTS" as hypertension_exists,
    "HYPERLIPIDAEMIA_EXISTS" as hyperlipidaemia_exists,
    "DIABETES_EXISTS" as diabetes_exists,
    "CHRONIC_KIDNEY_DISEASE_EXISTS" as chronic_kidney_disease_exists,
    "NA_FATTY_LIVER_DISEASE_EXISTS" as na_fatty_liver_disease_exists,
    "COPD_EXISTS" as copd_exists,
    "ASTHMA_EXISTS" as asthma_exists,
    "SERIOUS_MI_EXISTS" as serious_mi_exists,
    "LEARNING_DISABILITY_EXISTS" as learning_disability_exists,
    "FRAILTY_EXISTS" as frailty_exists,
    "SMOKING_STATUS_DATE" as smoking_status_date,
    "SMOKING_STATUS_CODE_TERM" as smoking_status_code_term,
    "SMOKING_STATUS_VALUE" as smoking_status_value,
    "BMI_DATE" as bmi_date,
    "BMI_CODE_TERM" as bmi_code_term,
    "BMI_VALUE" as bmi_value,
    "O_E_BP_READING_DATE" as o_e_bp_reading_date,
    "O_E_BP_READING_CODE_TERM" as o_e_bp_reading_code_term,
    "O_E_BP_READING_VALUE" as o_e_bp_reading_value,
    "O_E_BP_READING_SECONDARY_VALUE" as o_e_bp_reading_secondary_value,
    "HBA1C_DATE" as hba1_c_date,
    "HBA1C_CODE_TERM" as hba1_c_code_term,
    "HBA1C_VALUE" as hba1_c_value,
    "EGFR_DATE" as egfr_date,
    "EGFR_CODE_TERM" as egfr_code_term,
    "EGFR_VALUE" as egfr_value,
    "UACR_DATE" as uacr_date,
    "UACR_CODE_TERM" as uacr_code_term,
    "UACR_VALUE" as uacr_value,
    "TC_DATE" as tc_date,
    "TC_CODE_TERM" as tc_code_term,
    "TC_VALUE" as tc_value,
    "LDL_DATE" as ldl_date,
    "LDL_CODE_TERM" as ldl_code_term,
    "LDL_VALUE" as ldl_value,
    "MOC_CHECK_TEST_APPOINTMENT_ON_DATE" as moc_check_test_appointment_on_date,
    "MOC_FOLLOW_UP_APPOINTMENT_ON_DATE" as moc_follow_up_appointment_on_date,
    "RPT_COUNT_COUNT" as rpt_count_count,
    "RECORD_SOURCE" as record_source,
    "GP_PRACTICE_WARNING_FLAG" as gp_practice_warning_flag,
    "METADATA_FILE_PATH" as metadata_file_path,
    "METADATA_FILE_ROW_NUMBER" as metadata_file_row_number,
    "METADATA_RECORD_INGESTION_TIMESTAMP" as metadata_record_ingestion_timestamp,
    "METADATA_FILE_CONTENT_KEY" as metadata_file_content_key,
    "METADATA_FILE_LAST_MODIFIED" as metadata_file_last_modified
from {{ source('cltcs_emis_extract', 'EMIS') }}
