SELECT
    {{ consistent_sk_patient_id_format('pseudo_nhs_number')}} as sk_patient_id,  
    dmic_dec_month_of_birth,
    dec_sex,
    dec_marital_status,
    dec_agec,
    reg_date_of_death,
    reg_date,
    reg_district_code,
    reg_sub_district_code,
    reg_number,
    reg_entry_number,
    reg_type,
    cor_designation,
    cor_area_name,
    cor_inq_dates,
    dec_occ_type,
    out_seccatdm,
    out_seccathf,
    soc2_kdm,
    dmic_soc2_kdm_group_description,
    soc2_khf,
    dmic_soc2_khf_group_description,
    dec_retired_ind,
    dmic_decad_postcode_sector,
    dmic_decad_stat_postcode_sector,
    dec_birth_country_code,
    dmic_pod_stat_postcode_sector,
    pod_nhs_establishment,
    pod_establishment_type,
    pod_code,
    {{clean_icd10_code("s_underlying_cod_icd10")}} as s_underlying_cod_icd10,
    dmic_s_underlying_cod_icd10_chapter,
    {{clean_icd10_code("s_cod_code_1")}} as s_cod_code_1,
    {{clean_icd10_code("s_cod_code_2")}} as s_cod_code_2,
    {{clean_icd10_code("s_cod_code_3")}} as s_cod_code_3,
    {{clean_icd10_code("s_cod_code_4")}} as s_cod_code_4,
    {{clean_icd10_code("s_cod_code_5")}} as s_cod_code_5,
    {{clean_icd10_code("s_cod_code_6")}} as s_cod_code_6,
    {{clean_icd10_code("s_cod_code_7")}} as s_cod_code_7,
    {{clean_icd10_code("s_cod_code_8")}} as s_cod_code_8,
    {{clean_icd10_code("s_cod_code_9")}} as s_cod_code_9,
    {{clean_icd10_code("s_cod_code_10")}} as s_cod_code_10,
    {{clean_icd10_code("s_cod_code_11")}} as s_cod_code_11,
    {{clean_icd10_code("s_cod_code_12")}} as s_cod_code_12,
    {{clean_icd10_code("s_cod_code_13")}} as s_cod_code_13,
    {{clean_icd10_code("s_cod_code_14")}} as s_cod_code_14,
    {{clean_icd10_code("s_cod_code_15")}} as s_cod_code_15,
    s_injury_external,
    dmic_s_injury_external_icd10_chapter,
    s_cod_line_1,
    s_cod_line_2,
    s_cod_line_3,
    s_cod_line_4,
    s_cod_line_5,
    s_cod_line_6,
    s_cod_line_7,
    s_cod_line_8,
    s_cod_line_9,
    s_cod_line_10,
    s_cod_line_11,
    s_cod_line_12,
    s_cod_line_13,
    s_cod_line_14,
    s_cod_line_15,
    record_type,
    neo_nate_flag,
    cancelled_flag,
    -- CCGs were abolished in 2022 and replaced by sub-ICBs; the deaths
    -- source caught up in the same window as the OLIDS schema regen.
    -- Renamed: ccg_of_registration_code -> sub_icb_code_from_gp_practice_code,
    -- place_of_death_ccg_code -> place_of_death_sub_icb_code,
    -- ccg_of_residence_code -> sub_icb_of_residence_code.
    sub_icb_code_from_gp_practice_code,
    place_of_death_sub_icb_code,
    place_of_death_icb_code,
    place_of_death_org_code,
    place_of_death_ula_code,
    ula_of_residence_code,
    ward_of_residence_code,
    sub_icb_of_residence_code,
    icb_of_residence_code,
    county_district_of_res_code,
    county_of_residence_code,
    gor_of_residence_code,
    -- Upstream renamed lsoa_of_residence_code -> lsoa11_of_residence_code and
    -- added 2021-boundary LSOA/MSOA geographies alongside the 2011 codes.
    lsoa11_of_residence_code,
    lsoa21_of_residence_code,
    msoa11_of_residence_code,
    msoa21_of_residence_code,
    pco_of_residence_code,
    gp_practice_code,
    -- dmic_filename,
    -- dmic_operator,
    dmic_record_valid_date_from,
    dmic_record_valid_date_to,
    dmic_record_valid_is_latest,
    dmic_import_log_id,
    dmic_row_id,
    -- dm_icb_commissioner,
    -- dm_sub_icb_commissioner,
    -- dm_icb_registration_submitted,
    -- dm_icb_residence_submitted,
    -- dm_sub_icb_registration_submitted,
    -- dm_sub_icb_residence_submitted,
    -- dm_commissioner_derivation_reason
FROM {{ ref("raw_registries_deaths_deaths") }}